/**
 * @scalar GENERATED_CODE
 *
 * This file is auto-generated by the buildMdxElements function
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * This file can be safely added to the .gitignore file if desired.
 */

import type React from 'react'

export const components = {}

/**
 * This function is used to inject the components into the JSX context during the page build.
 *
 * It is used to avoid explicit imports of components in the MDX files.
 */
export function useMDXComponents(_components: Record<string, React.ComponentType<any>> = {}) {
  return {
    ..._components,
    ...components,
  }
}
