//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Scalar ASP.NET Core enum generator.
//     Source: /packages/snippetz/src/clients.ts
//     Command: pnpm generate:enums
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS0618 // Type or member is obsolete 
namespace Scalar.AspNetCore;

/// <summary>
/// Auto-generated mapping between targets and their available clients.
/// This partial class extends ScalarOptionsMapper with the generated mapping.
/// </summary>
internal static partial class ScalarOptionsMapper
{
    private static readonly Dictionary<ScalarTarget, ScalarClient[]> _targetToClientsMap = new()
    {
        { ScalarTarget.C, [ScalarClient.Libcurl] },
        { ScalarTarget.CSharp, [ScalarClient.HttpClient, ScalarClient.RestSharp] },
        { ScalarTarget.Clojure, [ScalarClient.CljHttp] },
        { ScalarTarget.Dart, [ScalarClient.Http] },
        { ScalarTarget.Go, [ScalarClient.Native] },
        { ScalarTarget.Http, [ScalarClient.Http11] },
        { ScalarTarget.Java, [ScalarClient.AsyncHttp, ScalarClient.NetHttp, ScalarClient.OkHttp, ScalarClient.Unirest] },
        { ScalarTarget.JavaScript, [ScalarClient.Fetch, ScalarClient.Axios, ScalarClient.OFetch, ScalarClient.JQuery, ScalarClient.Xhr] },
        { ScalarTarget.Kotlin, [ScalarClient.OkHttp] },
        { ScalarTarget.Node, [ScalarClient.Fetch, ScalarClient.Axios, ScalarClient.OFetch, ScalarClient.Undici] },
        { ScalarTarget.ObjC, [ScalarClient.NSUrlSession, ScalarClient.Nsurlsession] },
        { ScalarTarget.OCaml, [ScalarClient.CoHttp] },
        { ScalarTarget.Php, [ScalarClient.Curl, ScalarClient.Guzzle] },
        { ScalarTarget.PowerShell, [ScalarClient.WebRequest, ScalarClient.RestMethod] },
        { ScalarTarget.Python, [ScalarClient.Python3, ScalarClient.Requests, ScalarClient.HttpxSync, ScalarClient.HttpxAsync] },
        { ScalarTarget.R, [ScalarClient.Httr] },
        { ScalarTarget.Ruby, [ScalarClient.Native] },
        { ScalarTarget.Rust, [ScalarClient.Reqwest] },
        { ScalarTarget.Shell, [ScalarClient.Curl, ScalarClient.Wget, ScalarClient.Httpie] },
        { ScalarTarget.Swift, [ScalarClient.NSUrlSession, ScalarClient.Nsurlsession] },
    };

    internal static partial Dictionary<ScalarTarget, ScalarClient[]> AvailableClientsByTarget => _targetToClientsMap;
}