import { describe, expect, it } from 'vitest'

import {
  any,
  array,
  boolean,
  evaluate,
  lazy,
  intersection,
  literal,
  notDefined,
  nullable,
  number,
  object,
  optional,
  record,
  string,
  union,
} from '@/schema'
import { generateTypes } from '@/typegen'

const fixedGeneratedAt = '2000-01-01T00:00:00.000Z'

const autogeneratedBanner = `/**\n * This file is autogenerated. Do not edit it.\n *\n * Generated at: ${fixedGeneratedAt}\n */\n\n`

describe('typegen', () => {
  it('emits primitives and special scalars', () => {
    expect(generateTypes(number())).toBe('number')
    expect(generateTypes(string())).toBe('string')
    expect(generateTypes(boolean())).toBe('boolean')
    expect(generateTypes(nullable())).toBe('null')
    expect(generateTypes(notDefined())).toBe('undefined')
    expect(generateTypes(any())).toBe('any')
  })

  it('emits arrays with parentheses when the item is a union or intersection', () => {
    expect(generateTypes(array(number()))).toBe('number[]')
    expect(generateTypes(array(union([number(), string()])))).toBe('(number | string)[]')
    expect(generateTypes(array(intersection([object({ a: number() }), object({ b: string() })])))).toBe(
      '({\n  a: number;\n} & {\n  b: string;\n})[]',
    )
  })

  it('emits records and objects', () => {
    expect(generateTypes(record(string(), number()))).toBe('Record<string, number>')
    expect(
      generateTypes(
        object({
          id: number(),
          name: string(),
        }),
      ),
    ).toBe('{\n  id: number;\n  name: string;\n}')
    expect(generateTypes(object({}))).toBe('{}')
  })

  it('indents nested object properties', () => {
    const car = object({
      make: string(),
      model: string(),
      year: number(),
      test: object({ test: string() }),
    })
    expect(generateTypes(car)).toBe(
      '{\n  make: string;\n  model: string;\n  year: number;\n  test: {\n    test: string;\n  };\n}',
    )
  })

  it('extracts typeName into a single export and references by name', () => {
    const user = object(
      {
        id: number(),
        name: string(),
      },
      { typeName: 'User' },
    )
    expect(generateTypes(user, { generatedAt: fixedGeneratedAt })).toBe(
      `${autogeneratedBanner}export type User = {\n  id: number;\n  name: string;\n}`,
    )
  })

  it('does not duplicate named types when the same name appears multiple times', () => {
    const user = object({ id: number() }, { typeName: 'User' })
    const doc = object(
      {
        author: user,
        editor: user,
      },
      { typeName: 'Document' },
    )
    const out = generateTypes(doc, { generatedAt: fixedGeneratedAt })
    expect(out.match(/export type User/g)?.length).toBe(1)
    expect(out).toContain('author: User')
    expect(out).toContain('editor: User')
    expect(out).toContain('export type Document =')
  })

  it('includes typeComment as JSDoc on named exports', () => {
    const t = object({}, { typeName: 'Empty', typeComment: 'No fields.' })
    expect(generateTypes(t, { generatedAt: fixedGeneratedAt })).toBe(
      `${autogeneratedBanner}/** No fields. */\nexport type Empty = {}`,
    )
  })

  it('formats multi-line typeComment as a JSDoc block', () => {
    const t = object({}, { typeName: 'T', typeComment: 'Line 1\nLine 2' })
    expect(generateTypes(t, { generatedAt: fixedGeneratedAt })).toBe(
      `${autogeneratedBanner}/** \n * Line 1\n * Line 2\n */\nexport type T = {}`,
    )
  })

  it('prefixes file-style output with an autogenerated banner and timestamp', () => {
    const t = object({ x: number() }, { typeName: 'T' })
    const out = generateTypes(t, { generatedAt: fixedGeneratedAt })
    expect(out.startsWith(autogeneratedBanner)).toBe(true)
    expect(out).toContain('Generated at: 2000-01-01T00:00:00.000Z')
  })

  it('wraps named types in export namespace when namespace option is set', () => {
    const user = object(
      {
        id: number(),
        name: string(),
      },
      { typeName: 'User' },
    )
    expect(generateTypes(user, { generatedAt: fixedGeneratedAt, namespace: 'Models' })).toBe(
      `${autogeneratedBanner}export namespace Models {\n  export type User = {\n    id: number;\n    name: string;\n  }\n}\n`,
    )
  })

  it('keeps cross-references unqualified inside a namespace', () => {
    const user = object({ id: number() }, { typeName: 'User' })
    const doc = object({ author: user }, { typeName: 'Document' })
    const out = generateTypes(doc, { generatedAt: fixedGeneratedAt, namespace: 'Api' })
    expect(out).toContain('export namespace Api {')
    expect(out).toContain('author: User')
    expect(out.match(/export type User/g)?.length).toBe(1)
  })

  it('ignores namespace when it is not a valid TypeScript identifier', () => {
    const t = object({ x: number() }, { typeName: 'T' })
    const out = generateTypes(t, { generatedAt: fixedGeneratedAt, namespace: 'not-valid' })
    expect(out).not.toContain('export namespace')
    expect(out).toContain('export type T =')
  })

  it('includes typeComment as JSDoc on object properties', () => {
    const t = object({
      id: number({ typeComment: 'Unique id.' }),
      name: string({ typeComment: 'Display name.' }),
    })
    expect(generateTypes(t)).toBe('{\n  /** Unique id. */\n  id: number;\n  /** Display name. */\n  name: string;\n}')
  })

  it('indents multi-line property typeComment in nested objects', () => {
    const t = object({
      outer: string({ typeComment: 'A\nB' }),
      inner: object({
        x: number({ typeComment: 'Nested.' }),
      }),
    })
    expect(generateTypes(t)).toBe(
      '{\n  /** \n   * A\n   * B\n   */\n  outer: string;\n  inner: {\n    /** Nested. */\n    x: number;\n  };\n}',
    )
  })

  it('ignores invalid typeName and keeps inline shape', () => {
    const bad = object({ x: number() }, { typeName: 'not-valid' })
    expect(generateTypes(bad)).toBe('{\n  x: number;\n}')
  })

  it('quotes object keys that are not valid identifiers', () => {
    expect(generateTypes(object({ 'foo-bar': string() }))).toBe('{\n  "foo-bar": string;\n}')
  })

  it('emits unions and optionals', () => {
    expect(generateTypes(union([literal(1), literal(2)]))).toBe('1 | 2')
    expect(generateTypes(optional(number()))).toBe('number | undefined')
  })

  it('emits never for an empty union and unknown for an empty intersection', () => {
    expect(generateTypes(union([]))).toBe('never')
    expect(generateTypes(intersection([]))).toBe('unknown')
  })

  it('emits optional object properties with ? instead of | undefined', () => {
    expect(
      generateTypes(
        object({
          id: number(),
          name: optional(string()),
        }),
      ),
    ).toBe('{\n  id: number;\n  name?: string;\n}')
  })

  it('emits literal bigint', () => {
    expect(generateTypes(literal(10n))).toBe('10n')
  })

  it('unwraps evaluate to the inner schema type', () => {
    expect(generateTypes(evaluate((v) => v, number()))).toBe('number')
  })

  it('resolves lazy schemas', () => {
    const schema = lazy(() => object({ n: number() }))
    expect(generateTypes(schema)).toBe('{\n  n: number;\n}')
  })

  it('returns any when max depth is exhausted', () => {
    expect(generateTypes(number(), { maxDepth: 0 })).toBe('any')
  })
})
