import { parseReleaseNotes } from '@scalar/helpers/markdown/release-notes'

/**
 * Raw markdown source for the curated release notes. The file lives at
 * the root of `projects/scalar-app/` so it ships alongside the bundled
 * desktop and web builds, is editable by hand on patch releases, and is
 * the single source of truth shared with the `release-notes-generator`
 * command in `tooling/scripts` (which appends to the same file during
 * `pnpm changeset version`).
 */
import releaseNotesMarkdown from '@/../RELEASE_NOTES.md?raw'

import type { ReleaseNote } from '../types'

/**
 * Curated, user-facing release notes for the Scalar app.
 *
 * Entries are parsed from `projects/scalar-app/RELEASE_NOTES.md` at module
 * load. The markdown is the source of truth - do not edit this file to
 * add a new release; update `RELEASE_NOTES.md` instead (manually for a
 * one-off, or via the release-notes generator on a normal release).
 *
 * The release-notes generator folds the API client's CHANGELOG into the
 * same scalar-app entry on every release, so changes that technically
 * live in `@scalar/api-client` still surface in this list - the API
 * client is the headline dependency, and the modal reads as a single
 * release note for the parent app.
 *
 * Sorted newest first so the `WhatsNewModal` can rely on `releaseNotes[0]`
 * being the latest release.
 */
export const releaseNotes: ReleaseNote[] = parseReleaseNotes(releaseNotesMarkdown)
