import { parseReleaseNotes } from '@scalar/helpers/markdown/release-notes'

/**
 * Raw markdown source for the curated release notes. The file lives at the
 * root of the package so it ships in the published tarball, is editable
 * by hand on patch releases, and is the single source of truth shared
 * with `tooling/release-notes-generator` (which appends to the same file
 * during `pnpm changeset version`).
 */
import releaseNotesMarkdown from '../../../../../RELEASE_NOTES.md?raw'
import type { ReleaseNote } from '../types'

/**
 * Curated, user-facing release notes for the API client.
 *
 * Entries are parsed from `packages/api-client/RELEASE_NOTES.md` at module
 * load. The markdown is the source of truth - do not edit this file to
 * add a new release; update `RELEASE_NOTES.md` instead (manually for a
 * one-off, or via the release-notes generator on a normal release).
 *
 * Sorted newest first so the `WhatsNewModal` can rely on `releaseNotes[0]`
 * being the latest release.
 */
export const releaseNotes: ReleaseNote[] = parseReleaseNotes(releaseNotesMarkdown)
