/**
 * Generate types for the schemas.
 *
 * Dumps the generated `.ts` files into the `@scalar/types` package, which is intentionally
 * dependency-free (pure types, no runtime). This script is the single source of truth for those files.
 *
 * Steps:
 *   1. Top-level schemas: API reference configuration and AsyncAPI 3.1 document.
 *   2. Extension folders: one merged `.ts` per entity folder in `schemas/src/extensions/`,
 *      plus a barrel that re-exports each entity as a namespace.
 *   3. Format every output path with biome so emitted files match repo style.
 *
 * Files are only rewritten when their body changes — the banner timestamp alone never triggers a write.
 */

import { spawnSync } from 'node:child_process'
import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

import { type Schema, generateTypes } from '@scalar/validation'

import { apiReferenceConfigurationSchema } from '../src/api-reference/api-reference-configuration'
import { createAsyncApiObjectSchema } from '../src/asyncapi/3.1/asyncapi-object'
import { recursiveRef } from '../src/asyncapi/3.1/reference'
import {
  GENERATED_TYPE_EXTENSIONS_PATH,
  GENERATED_TYPE_OUTPUT_PATHS,
  getGeneratedTypeAbsolutePaths,
  getRepoRoot,
} from './generated-type-paths'

// ─── Constants ─────────────────────────────────────────────────────────────────

const GENERATED_AT = new Date().toISOString()

/** Shared options passed to every `generateTypes` call. */
const TYPEGEN_OPTIONS = {
  generatedAt: GENERATED_AT,
  maxDepth: Number.POSITIVE_INFINITY,
} as const

/** Matches the banner emitted at the top of every generated file. The timestamp inside is volatile. */
const AUTOGENERATED_BANNER_RE =
  /^\/\*\*\n \* This file is autogenerated\. Do not edit it\.\n \*\n \* Generated at: [\s\S]*?\*\/\n\n/

/** Matches a single typegen output chunk: an optional JSDoc block followed by `export type Name = ...`. */
const TYPE_DECLARATION_RE =
  /(?:\/\*\*[\s\S]*?\*\/\s*\n)?export type [$_A-Za-z][$_\w]* = [\s\S]*?(?=\n\n(?:\/\*\*[\s\S]*?\*\/\s*\n)?export type |$)/g

const SCHEMAS_ROOT = path.join(import.meta.dirname, '../src')
const TYPES_ROOT = path.join(import.meta.dirname, '../../types/src')
const EXTENSIONS_INPUT_ROOT = path.join(SCHEMAS_ROOT, 'extensions')
const EXTENSIONS_OUTPUT_ROOT = path.join(TYPES_ROOT, 'extensions')

/** Repo-root-relative paths handed to biome at the end of the run. */
const BIOME_FORMAT_PATHS = [...GENERATED_TYPE_OUTPUT_PATHS, GENERATED_TYPE_EXTENSIONS_PATH] as const

// ─── Generated file IO ─────────────────────────────────────────────────────────

const formatBanner = (at: string): string =>
  `/**\n * This file is autogenerated. Do not edit it.\n *\n * Generated at: ${at}\n */\n\n`

const stripBanner = (content: string): string => content.replace(AUTOGENERATED_BANNER_RE, '').trim()

/** Two generated files are equivalent when only the banner timestamp differs. */
const hasSameBody = (a: string, b: string): boolean => stripBanner(a) === stripBanner(b)

/**
 * Format `content` the same way the post-generation biome pass would, so comparisons match on-disk files.
 *
 * Biome resolves config by walking up from the file path, not from `cwd`. Temp files live under
 * `os.tmpdir()`, so pass `--config-path` explicitly to use the repo `biome.json`.
 *
 * Falls back to the raw string when biome fails (for example in a stripped-down environment).
 */
const formatWithBiome = async (content: string, filePath: string, repoRoot: string): Promise<string> => {
  const biomeConfigPath = path.join(repoRoot, 'biome.json')
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'scalar-types-'))
  try {
    const tmpFile = path.join(tmpDir, path.basename(filePath))
    await fs.writeFile(tmpFile, content, 'utf8')
    const result = spawnSync('pnpm', ['biome', 'format', '--write', '--config-path', biomeConfigPath, tmpFile], {
      cwd: repoRoot,
      stdio: 'pipe',
    })
    if (result.status !== 0) {
      return content
    }
    return await fs.readFile(tmpFile, 'utf8')
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true })
  }
}

/**
 * Write `content` to `filePath`, but skip the write when only the banner timestamp would change.
 *
 * Compares against the on-disk file after formatting the candidate with biome, because committed
 * outputs are always biome-formatted while typegen emits unformatted text.
 *
 * Returns `true` when the file was actually written, `false` when it was already up to date.
 */
const writeIfChanged = async (filePath: string, content: string, repoRoot: string): Promise<boolean> => {
  try {
    const existing = await fs.readFile(filePath, 'utf8')
    const formattedCandidate = await formatWithBiome(content, filePath, repoRoot)
    if (hasSameBody(existing, formattedCandidate)) {
      return false
    }
  } catch {
    // File does not exist yet — fall through and write.
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true })
  await fs.writeFile(filePath, content)
  return true
}

// ─── Schema and typegen helpers ────────────────────────────────────────────────

const isSchema = (value: unknown): value is Schema =>
  typeof value === 'object' && value !== null && 'type' in value && typeof value.type === 'string'

/** Extract the type name from a single `export type Name = ...` chunk. */
const getDeclarationName = (chunk: string): string | undefined =>
  chunk.match(/^export type ([$_A-Za-z][$_\w]*) =/m)?.[1]

/** Split a typegen output string into individual `export type` declaration chunks (with their JSDoc). */
const splitTypeDeclarations = (content: string): string[] => {
  const body = stripBanner(content)
  if (!body) {
    return []
  }

  return [...body.matchAll(TYPE_DECLARATION_RE)].map((match) => match[0].trimEnd())
}

/** Generate types for a single named schema with the shared {@link TYPEGEN_OPTIONS}. */
const generateNamedTypes = (schema: Schema, typeName: string): string =>
  generateTypes(schema, { ...TYPEGEN_OPTIONS, typeName })

/**
 * Generate types for multiple schemas and merge them into a single file body, deduplicating by type name.
 *
 * When two schemas emit the same `export type Name`, the first occurrence wins. This keeps the merged
 * file deterministic when extension schemas share helper types.
 */
const mergeSchemaTypes = (schemas: Schema[]): string => {
  const declarations = new Map<string, string>()

  for (const schema of schemas) {
    const output = generateTypes(schema, TYPEGEN_OPTIONS)
    for (const chunk of splitTypeDeclarations(output)) {
      const name = getDeclarationName(chunk)
      if (name && !declarations.has(name)) {
        declarations.set(name, chunk)
      }
    }
  }

  return `${formatBanner(GENERATED_AT)}${[...declarations.values()].join('\n\n')}\n`
}

// ─── Folder helpers ────────────────────────────────────────────────────────────

/** List immediate subfolders of `root` in sorted order. */
const listSubfolders = async (root: string): Promise<string[]> => {
  const entries = await fs.readdir(root, { withFileTypes: true })
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
}

/**
 * Dynamically import the `index.ts` at `folderPath` and return its named Schema exports,
 * sorted by export name for deterministic typegen output.
 */
const loadSchemasFromIndex = async (folderPath: string): Promise<Schema[]> => {
  const indexPath = path.join(folderPath, 'index.ts')
  const module = (await import(pathToFileURL(indexPath).href)) as Record<string, unknown>

  return Object.entries(module)
    .filter((entry): entry is [string, Schema] => isSchema(entry[1]))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, schema]) => schema)
}

/** Convert a folder name (`document`) to its barrel namespace identifier (`Document`). */
const toNamespaceIdentifier = (folder: string): string => folder.charAt(0).toUpperCase() + folder.slice(1)

/** Build a barrel file body: one `export type * as <Namespace> from './<folder>'` line per folder. */
const buildNamespacedBarrel = (folders: string[]): string => {
  const exports = folders
    .map((folder) => `export type * as ${toNamespaceIdentifier(folder)} from './${folder}'`)
    .join('\n')
  return `${formatBanner(GENERATED_AT)}${exports}\n`
}

// ─── Write tally ───────────────────────────────────────────────────────────────

type WriteTally = {
  written: number
  skipped: number
  record: (didWrite: boolean) => void
}

/** Small counter that aggregates results from `writeIfChanged` for the final summary log. */
const createWriteTally = (): WriteTally => {
  const tally = {
    written: 0,
    skipped: 0,
    record(didWrite: boolean) {
      if (didWrite) {
        tally.written++
      } else {
        tally.skipped++
      }
    },
  }
  return tally
}

// ─── High-level generators ─────────────────────────────────────────────────────

type TopLevelTarget = {
  /** Schema to generate types from. */
  schema: Schema
  /** Name to use for the root `export type`. */
  typeName: string
  /** Absolute path of the file to write. */
  outputPath: string
}

/** Generate one named type file per target, recording each write in `tally`. */
const generateTopLevelTypes = async (
  targets: readonly TopLevelTarget[],
  tally: WriteTally,
  repoRoot: string,
): Promise<void> => {
  for (const { schema, typeName, outputPath } of targets) {
    const content = generateNamedTypes(schema, typeName)
    tally.record(await writeIfChanged(outputPath, content, repoRoot))
  }
}

type NamespacedFolderTarget = {
  /** Root directory containing entity subfolders. Each subfolder's `index.ts` is expected to export schemas. */
  inputRoot: string
  /** Root directory to write `<folder>/index.ts` files and the namespaced barrel into. */
  outputRoot: string
}

/**
 * Generate a merged types file per immediate subfolder of `inputRoot`, plus a barrel that re-exports
 * each subfolder as a namespace at `outputRoot/index.ts`.
 *
 * Returns the list of folder names that were processed (sorted).
 */
const generateNamespacedFolderTypes = async (
  target: NamespacedFolderTarget,
  tally: WriteTally,
  repoRoot: string,
): Promise<string[]> => {
  const folders = await listSubfolders(target.inputRoot)

  for (const folder of folders) {
    const schemas = await loadSchemasFromIndex(path.join(target.inputRoot, folder))
    const types = mergeSchemaTypes(schemas)
    tally.record(await writeIfChanged(path.join(target.outputRoot, folder, 'index.ts'), types, repoRoot))
  }

  const barrel = buildNamespacedBarrel(folders)
  tally.record(await writeIfChanged(path.join(target.outputRoot, 'index.ts'), barrel, repoRoot))

  return folders
}

// ─── Biome formatter ───────────────────────────────────────────────────────────

/** Run `biome check --write` on the given paths. Exits the process when biome reports a non-zero status. */
const runBiomeFormat = (paths: readonly string[], cwd: string): void => {
  const result = spawnSync(
    'pnpm',
    [
      'biome',
      'check',
      '--write',
      '--diagnostic-level=error',
      '--no-errors-on-unmatched',
      '--files-ignore-unknown=true',
      ...paths,
    ],
    { cwd, stdio: 'inherit' },
  )

  if (result.status !== 0) {
    process.exit(result.status ?? 1)
  }
}

// ─── Main ──────────────────────────────────────────────────────────────────────

const main = async (): Promise<void> => {
  const repoRoot = getRepoRoot()
  const generatedTypePaths = getGeneratedTypeAbsolutePaths(repoRoot)
  const tally = createWriteTally()

  await generateTopLevelTypes(
    [
      {
        schema: apiReferenceConfigurationSchema,
        typeName: 'ApiReferenceConfiguration',
        outputPath: generatedTypePaths[0],
      },
      {
        schema: createAsyncApiObjectSchema(recursiveRef),
        typeName: 'AsyncApiDocument',
        outputPath: generatedTypePaths[1],
      },
    ],
    tally,
    repoRoot,
  )

  const extensionFolders = await generateNamespacedFolderTypes(
    { inputRoot: EXTENSIONS_INPUT_ROOT, outputRoot: EXTENSIONS_OUTPUT_ROOT },
    tally,
    repoRoot,
  )

  console.log(
    `Generated types for ${extensionFolders.length} extension folders in ${EXTENSIONS_OUTPUT_ROOT} (${tally.written} written, ${tally.skipped} unchanged)`,
  )

  if (tally.written > 0) {
    runBiomeFormat(BIOME_FORMAT_PATHS, repoRoot)
  }
}

await main()
