/**
 * Generate types for the schemas
 *
 * We will dump the types to the types package which is going to be pure types with no dependencies on the schemas package
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { pathToFileURL } from 'node:url'

import { type Schema, generateTypes } from '@scalar/validation'

import { apiReferenceConfigurationSchema } from '../src/api-reference/api-reference-configuration'

const generatedAt = new Date().toISOString()

const typegenOptions = {
  generatedAt,
  maxDepth: Number.POSITIVE_INFINITY,
} as const

const AUTOGENERATED_BANNER_RE =
  /^\/\*\*\n \* This file is autogenerated\. Do not edit it\.\n \*\n \* Generated at: [\s\S]*?\*\/\n\n/

const formatAutogeneratedFileBanner = (at: string): string =>
  `/**\n * This file is autogenerated. Do not edit it.\n *\n * Generated at: ${at}\n */\n\n`

const stripAutogeneratedBanner = (content: string): string => content.replace(AUTOGENERATED_BANNER_RE, '').trim()

/** Compare generated output ignoring the autogenerated banner timestamp. */
const isEquivalentGeneratedContent = (existing: string, next: string): boolean =>
  stripAutogeneratedBanner(existing) === stripAutogeneratedBanner(next)

/** Write only when the file is missing or the body changed (not just the banner). */
const writeGeneratedFile = async (filePath: string, content: string): Promise<boolean> => {
  try {
    const existing = await fs.readFile(filePath, 'utf8')
    if (isEquivalentGeneratedContent(existing, content)) {
      return false
    }
  } catch {
    // File does not exist yet — write below.
  }

  await fs.writeFile(filePath, content)
  return true
}

const isSchema = (value: unknown): value is Schema =>
  typeof value === 'object' && value !== null && 'type' in value && typeof value.type === 'string'

const getDeclarationName = (chunk: string): string | undefined => {
  const match = chunk.match(/^export type ([$_A-Za-z][$_\w]*) =/m)
  return match?.[1]
}

/** Split typegen output into declaration chunks (optional JSDoc + `export type`). */
const splitTypeDeclarations = (content: string): string[] => {
  const trimmed = stripAutogeneratedBanner(content)
  if (!trimmed) {
    return []
  }

  const declarationPattern =
    /(?:\/\*\*[\s\S]*?\*\/\s*\n)?export type [$_A-Za-z][$_\w]* = [\s\S]*?(?=\n\n(?:\/\*\*[\s\S]*?\*\/\s*\n)?export type |$)/g

  return [...trimmed.matchAll(declarationPattern)].map((match) => match[0].trimEnd())
}

const mergeSchemaTypes = (schemas: Schema[]): string => {
  const declarations = new Map<string, string>()

  for (const schema of schemas) {
    const output = generateTypes(schema, typegenOptions)
    for (const chunk of splitTypeDeclarations(output)) {
      const name = getDeclarationName(chunk)
      if (name && !declarations.has(name)) {
        declarations.set(name, chunk)
      }
    }
  }

  const body = [...declarations.values()].join('\n\n')
  return `${formatAutogeneratedFileBanner(generatedAt)}${body}\n`
}

const schemasRoot = path.join(import.meta.dirname, '../src')
const extensionsRoot = path.join(schemasRoot, 'extensions')
const typesRoot = path.join(import.meta.dirname, '../../types/src')

/** Generate api-reference configuration types */
const apiReferenceConfigurationTypes = generateTypes(apiReferenceConfigurationSchema, {
  ...typegenOptions,
  typeName: 'ApiReferenceConfiguration',
})

const genDir = path.join(typesRoot, 'gen')
await fs.mkdir(genDir, { recursive: true })

let writtenCount = 0
let skippedCount = 0

if (await writeGeneratedFile(path.join(genDir, 'api-reference.d.ts'), apiReferenceConfigurationTypes)) {
  writtenCount++
} else {
  skippedCount++
}

/** Generate OpenAPI extension types per entity folder */
const extensionFolders = (
  await fs.readdir(extensionsRoot, {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()

const extensionsOutRoot = path.join(typesRoot, 'extensions')
await fs.mkdir(extensionsOutRoot, { recursive: true })

for (const folder of extensionFolders) {
  const indexPath = path.join(extensionsRoot, folder, 'index.ts')
  const module = await import(pathToFileURL(indexPath).href)

  const schemas = Object.entries(module)
    .filter((entry): entry is [string, Schema] => isSchema(entry[1]))
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([, schema]) => schema)

  const types = mergeSchemaTypes(schemas)
  const outDir = path.join(extensionsOutRoot, folder)
  await fs.mkdir(outDir, { recursive: true })
  if (await writeGeneratedFile(path.join(outDir, 'index.ts'), types)) {
    writtenCount++
  } else {
    skippedCount++
  }
}

const toExtensionNamespace = (folder: string): string => folder.charAt(0).toUpperCase() + folder.slice(1)

const extensionsBarrel = `${formatAutogeneratedFileBanner(generatedAt)}${extensionFolders.map((folder) => `export type * as ${toExtensionNamespace(folder)} from './${folder}'`).join('\n')}\n`

if (await writeGeneratedFile(path.join(extensionsOutRoot, 'index.ts'), extensionsBarrel)) {
  writtenCount++
} else {
  skippedCount++
}

console.log(
  `Generated types for ${extensionFolders.length} extension folders in ${extensionsOutRoot} (${writtenCount} written, ${skippedCount} unchanged)`,
)
