steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-base'
    args:
      [
        'build',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-f',
        './tooling/base-docker-builder/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-base'
    waitFor: ['build-base']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}']
  # ---------------------------------------------------------------
  # NextJS integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-next-js'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_NEXT_JS}',
        '-f',
        './examples/nextjs-api-reference/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-next-js'
    waitFor: ['build-next-js']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NEXT_JS}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-next-js']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NEXT_JS',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_NEXT_JS}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # React integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-react-js'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_REACT_JS}',
        '-f',
        './examples/react/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-react-js'
    waitFor: ['build-react-js']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_REACT_JS}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-react-js']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_REACT_JS',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_REACT_JS}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # Fastify integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-fastify'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_FASTIFY}',
        '-f',
        './examples/fastify-api-reference/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-fastify'
    waitFor: ['build-fastify']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_FASTIFY}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-fastify']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_FASTIFY',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_FASTIFY}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # Hono integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-hono'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_HONO}',
        '-f',
        './examples/hono-api-reference/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-hono'
    waitFor: ['build-hono']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_HONO}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-hono']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_HONO',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_HONO}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # NestJS Express integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-nest-js-express'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_NEST_JS_EXPRESS}',
        '-f',
        './examples/nestjs-api-reference-express/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-nest-js-express'
    waitFor: ['build-nest-js-express']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NEST_JS_EXPRESS}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-nest-js-express']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NEST_JS_EXPRESS',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_NEST_JS_EXPRESS}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # Express integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-express-js'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_EXPRESS}',
        '-f',
        './examples/express-api-reference/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-express-js'
    waitFor: ['build-express-js']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_EXPRESS}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-express-js']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_EXPRESS',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_EXPRESS}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # NestJS Fastify integration
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-nest-js-fastify'
    waitFor: ['push-base']
    args:
      [
        'buildx',
        'build',
        '--build-arg',
        'BASE_IMAGE=gcr.io/${_PROJECT_ID}/${_BASE_BUILDER}',
        '-t',
        'gcr.io/${_PROJECT_ID}/${_SERVICE_NEST_JS_FASTIFY}',
        '-f',
        './examples/nestjs-api-reference-fastify/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-nest-js-fastify'
    waitFor: ['build-nest-js-fastify']
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_SERVICE_NEST_JS_FASTIFY}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    waitFor: ['push-nest-js-fastify']
    args:
      [
        'run',
        'deploy',
        '$_SERVICE_NEST_JS_FASTIFY',
        '--image=gcr.io/${_PROJECT_ID}/${_SERVICE_NEST_JS_FASTIFY}',
        '--region=$_REGION',
        '--platform=managed',
        '--allow-unauthenticated',
        '--execution-environment=gen2',
        '--cpu=$_CPU',
        '--memory=$_MEMORY',
        '--service-account=$_SERVICE_ACCOUNT',
      ]
  # ---------------------------------------------------------------
  # Other Integration
  # - name: OTHER INTEGRATION
# ---------------------------------------------------------------
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
