packages:
  - examples/**/*
  - integrations/**/*
  - packages/**/*
  - playwright
  - scripts
  - projects/**/*
  - '!**/.next/**'
  - '!**/dist/**'
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@todesktop/cli'
  - core-js
  - core-js-pure
  - electron
  - lefthook
  - vue-demi
catalogs:
  '*':
    '@types/express': ^5.0.1
    '@types/node': ^20.17.10
    '@vitejs/plugin-vue': ^5.0.4
    '@vueuse/core': ^10.10.0
    '@tailwindcss/vite': ^4.1.7
    '@types/picomatch': 3.0.1
    '@types/semver': 7.5.8
    ansis: 3.16.0
    concurrently: 9.1.2
    esbuild: 0.25.2
    chokidar: 4.0.3
    commander: 13.1.0
    express: ^5.1.0
    nanoid: ^5.1.5
    next: ^15.2.3
    postcss: ^8.4.38
    tailwindcss: ^4.1.7
    type-fest: ^4.20.0
    vite: 5.4.19
    vitest: ^1.6.0
    vue: ^3.5.12
    yaml: ^2.4.5
    zod: 3.24.1
    picomatch: 4.0.2
    stdout-update: 4.0.1
    semver: 7.6.3
    prettier: 3.5.3
    vite-node: 3.1.1
    rollup: 4.40.1
