packages:
  - examples/**/*
  - integrations/**/*
  - packages/**/*
  - playwright
  - scripts
  - projects/**/*
  - '!**/.next/**'
  - '!**/dist/**'
  - '!**/.output/**'
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@todesktop/cli'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - lefthook
  - vue-demi
catalogs:
  '*':
    '@fastify/swagger': ^8.10.1
    '@floating-ui/utils': ^0.2.2
    '@floating-ui/vue': ^1.1.7
    '@google-cloud/storage': 7.16.0
    '@headlessui/tailwindcss': ^0.2.2
    '@headlessui/vue': ^1.7.23
    '@playwright/test': 1.54.0
    '@sinclair/typebox': https://raw.githubusercontent.com/DemonHa/typebox/refs/heads/amrit/build-2/target/sinclair-typebox-0.34.40.tgz
    '@tailwindcss/vite': ^4.1.7
    '@types/express': 5.0.3
    '@types/node': ^22.9.0
    '@types/picomatch': 3.0.1
    '@types/react-dom': ^19.1.6
    '@types/react': ^19.1.8
    '@types/semver': 7.5.8
    '@typescript-eslint/parser': ^8.0.0
    '@vueuse/core': ^11.2.0
    '@vitejs/plugin-vue': ^5.2.4
    '@vueuse/integrations': ^11.2.0
    '@vue/test-utils': ^2.4.1
    ansis: 4.1.0
    chokidar: 4.0.3
    commander: 13.1.0
    concurrently: 9.1.2
    esbuild: 0.25.6
    express: 5.1.0
    fastify: ^5.3.3
    flatted: ^3.3.3
    fuse.js: ^7.1.0
    microdiff: ^1.5.0
    nanoid: 5.1.5
    next: ^15.3.3
    picomatch: 4.0.2
    postcss: ^8.4.38
    prettier: 3.5.3
    react-dom: ^19.1.0
    react: ^19.1.0
    rollup: 4.45.1
    semver: 7.7.2
    stdout-update: 4.0.1
    tailwindcss: ^4.1.7
    type-fest: 4.41.0
    vite-node: 3.2.4
    vite: 6.1.6
    vitest: ^3.2.4
    vue: ^3.5.17
    yaml: 2.8.0
    zod: 3.24.1
