packages:
  - 'examples/**/*'
  - 'integrations/**/*'
  - 'packages/**/*'
  - 'playwright'
  - 'projects/**/*'
  - '!**/.next/**' # To prevent next.js duplicates
  - '!**/dist/**' # To prevent dist duplicates
