packages:
  - 'examples/**/*'
  - 'integrations/**/*'
  - 'packages/**/*'
  - 'playwright'
  - 'projects/**/*'
  - '!**/.next/**' # To prevent next.js duplicates
  - '!**/dist/**' # To prevent dist duplicates
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@todesktop/cli'
  - core-js
  - core-js-pure
  - electron
  - lefthook
  - vue-demi
ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - dtrace-provider
  - esbuild
  - msw
  - protobufjs
  - sharp
  - workerd
catalog:
  '@types/express': ^5.0.1
  '@types/node': ^20.17.10
  '@vitejs/plugin-vue': ^5.0.4
  '@vueuse/core': ^10.10.0
  express: ^5.1.0
  nanoid: ^5.1.5
  next: ^15.2.3
  postcss: ^8.4.38
  tailwindcss: ^3.4.4
  type-fest: ^4.20.0
  vite: ^5.4.10
  vitest: ^1.6.0
  vue: ^3.5.12
  yaml: ^2.4.5
  zod: ^3.23.8
