packages:
  - examples/**/*
  - integrations/**/*
  - packages/**/*
  - playwright
  - tooling/scripts
  - tooling/changelog-generator
  - projects/**/*
  - '!**/.next/**'
  - '!**/dist/**'
  - '!**/.output/**'
  - '!**/target/**'

catalogs:
  '*':
    '@ai-sdk/vue': 3.0.33
    '@fastify/basic-auth': ^5.1.1
    '@fastify/http-proxy': ^9.5.0
    '@fastify/swagger': ^8.10.1
    '@floating-ui/utils': 0.2.10
    '@floating-ui/vue': 1.1.9
    '@google-cloud/storage': 7.16.0
    '@headlessui/tailwindcss': ^0.2.2
    '@headlessui/vue': 1.7.23
    '@hono/node-server': ^1.19.7
    '@modelcontextprotocol/sdk': 1.25.2
    '@nestjs/cli': '^11.0.14'
    '@nestjs/common': '^11.1.11'
    '@nestjs/core': '^11.1.11'
    '@nestjs/platform-express': '^11.1.11'
    '@nestjs/platform-fastify': '^11.1.11'
    '@nestjs/schematics': '^11.0.9'
    '@nestjs/swagger': '^7.3.1'
    '@nestjs/testing': '^11.1.11'
    '@playwright/test': 1.56.0
    '@scalar/typebox': 0.1.3
    '@scalar/agent-chat': 0.2.3
    '@tailwindcss/vite': ^4.1.18
    '@types/express': 5.0.3
    '@types/jsdom': 27.0.0
    '@types/node': ^22.19.3
    '@types/picomatch': 4.0.2
    '@types/react-dom': ^19.2.3
    '@types/react': ^19.2.7
    '@types/semver': 7.5.8
    '@types/supertest': 6.0.2
    '@types/whatwg-mimetype': 3.0.2
    '@typescript-eslint/parser': ^8.53.0
    '@vitejs/plugin-react': 5.0.4
    '@vitejs/plugin-vue': ^6.0.3
    '@vue/test-utils': 2.4.6
    '@vueuse/core': 13.9.0
    '@vueuse/integrations': 13.9.0
    'fastify-plugin': ^4.5.1
    'pretty-bytes': ^7.1.0
    ai: 6.0.33
    ansis: 4.1.0
    astro: 5.15.9
    chokidar: 5.0.0
    commander: 13.1.0
    concurrently: 9.1.2
    esbuild: 0.25.6
    express: 5.1.0
    fake-indexeddb: 6.2.3
    fast-glob: ^3.3.3
    fastify: ^5.3.3
    flatted: ^3.3.3
    fuse.js: ^7.1.0
    hono: 4.11.7
    js-base64: ^3.7.8
    jsdom: 27.4.0
    microdiff: ^1.5.0
    nanoid: ^5.1.6
    next: ^15.5.10
    neverpanic: 0.0.5
    picomatch: ^4.0.2
    postcss: ^8.4.38
    react-dom: ^19.2.3
    react: ^19.2.3
    semver: 7.7.2
    shx: ^0.4.0
    supertest: '7.2.2'
    tailwindcss: ^4.1.18
    type-fest: ^5.3.1
    truncate-json: 3.0.1
    vite-node: 5.2.0
    vite-ssg: 28.1.0
    vite-svg-loader: 5.1.0
    vite: ^7.3.1
    vitest: 4.0.16
    vue-router: 4.6.2
    vue-tsc: ^2.2.0
    vue: ^3.5.26
    whatwg-mimetype: 4.0.0
    yaml: ^2.8.0
    zod: ^4.3.5
ignoredBuiltDependencies:
  - '@firebase/util'
  - core-js
  - core-js-pure
  - dtrace-provider
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@astrojs/*'
  - '@next/*'
  - '@nestjs/*'
  - astro
  - hono
  - next
  - vite
  - vite-node
  - vitest
  - vue
  - '@modelcontextprotocol/sdk@1.26.0'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@todesktop/cli'
  - electron
  - esbuild
  - lefthook
