packages:
  - 'examples/*'
  - 'integrations/*'
  - 'integrations/express-api-reference/playground'
  - 'packages/*'
  - 'packages/api-reference/docker'
  - 'packages/fastify-api-reference/playground'
  - 'packages/snippetz/playground'
  - 'playwright'
  - 'projects/*'
