/**
 * Serialize curated release notes into the human-readable `RELEASE_NOTES.md`
 * shape used as a derived view next to `RELEASE_NOTES.json`.
 *
 * The Scalar app's "What's new" modal reads structured data from JSON at
 * build time; this module exists so the release-notes generator can still
 * emit a markdown file for humans browsing the repo without maintaining a
 * second hand-written format.
 *
 * Format (one entry per release, caller supplies order — newest first):
 *
 * ```markdown
 * ## 3.5.1 (2026-04-25)
 *
 * ### Smoother request runs and a friendlier slugger
 *
 * A small follow-up to the 3.5.0 release ...
 *
 * - Pending edits are now flushed before a request runs.
 * - Switched to our own slug generator.
 *
 * Rich blocks (images, extra headings) follow the same pattern inside the
 * entry body after the title line.
 *
 * [Read full release notes](https://github.com/scalar/scalar/releases/tag/%40scalar%2Fapi-client%403.5.1)
 * ```
 *
 * Anything before the first `## ` heading is the preamble (passed in via
 * `serializeReleaseNotes` options or defaulted).
 */

/** Free-form paragraph of plain text. */
export type ParagraphBlock = {
  type: 'paragraph'
  text: string
}

/** Subsection heading inside a release entry. Defaults to level 3. */
export type HeadingBlock = {
  type: 'heading'
  text: string
  level?: 3 | 4
}

/** Bullet (or numbered) list. */
export type ListBlock = {
  type: 'list'
  items: string[]
  ordered?: boolean
}

/** Inline image with optional caption. */
export type ImageBlock = {
  type: 'image'
  src: string
  alt: string
  caption?: string
  width?: number
  height?: number
}

/** Inline video clip with optional caption and playback hints. */
export type VideoBlock = {
  type: 'video'
  src: string
  poster?: string
  caption?: string
  autoplay?: boolean
  loop?: boolean
  muted?: boolean
  controls?: boolean
}

export type HrefBlock = {
  type: 'href'
  href: string
  label: string
}

/** Rich content block rendered between other blocks inside a release entry. */
export type ContentBlock = ParagraphBlock | HeadingBlock | ListBlock | ImageBlock | VideoBlock | HrefBlock

/** One release note row. Mirrors the Scalar app's `ReleaseNote` shape. */
export type ReleaseNoteEntry = {
  /** Semver-style version string (for example `3.5.1`). */
  version: string
  /** Release date in `YYYY-MM-DD` format. */
  date: string
  /** Short, sentence-case headline. */
  title: string
  /** Optional body: paragraphs, lists, headings, images, videos, and links. */
  content?: ContentBlock[]
}

/**
 * Default file preamble. Used by `serializeReleaseNotes` when no preamble
 * is supplied so the generator never accidentally writes a headerless file.
 *
 * The accompanying `RELEASE_NOTES.json` is the source of truth - this
 * markdown file is a human-friendly view that gets regenerated on every
 * release. Edits made directly to the markdown will be overwritten.
 */
export const DEFAULT_RELEASE_NOTES_PREAMBLE = `# Release notes

<!--
  Auto-generated by the \`release-notes-generator\` command in
  \`tooling/scripts\` on every release. Newest entries on top.

  Source of truth: \`RELEASE_NOTES.json\` next to this file. The Scalar
  app's "What's new" modal imports the JSON directly; this markdown file
  is a derived, human-friendly view that gets regenerated on every
  release - edits made directly here will be overwritten.
-->
`

/**
 * Serialize a list of entries into a `RELEASE_NOTES.md` document.
 * Entries are emitted in the order provided - callers should sort newest
 * first before calling this function.
 *
 * The output is deterministic for a given preamble and entry list.
 */
export const serializeReleaseNotes = (entries: ReleaseNoteEntry[], options: { preamble?: string } = {}): string => {
  const preamble = options.preamble ?? DEFAULT_RELEASE_NOTES_PREAMBLE
  const sections = entries.map(serializeEntry)
  const body = sections.join('\n')

  // Always end with a single trailing newline so the file plays nicely
  // with text-editing tools and POSIX expectations.
  const preambleBlock = preamble.replace(/\s+$/, '')
  return `${preambleBlock}\n\n${body.trimEnd()}\n`
}

const serializeEntry = (entry: ReleaseNoteEntry): string => {
  const blocks: string[] = []
  blocks.push(`## ${entry.version} (${entry.date})`)
  blocks.push(`### ${entry.title}`)
  if (entry.content && entry.content.length > 0) {
    for (const block of entry.content) {
      const rendered = serializeContentBlock(block)
      if (rendered) {
        blocks.push(rendered)
      }
    }
  }
  return `${blocks.join('\n\n')}\n`
}

/**
 * Render a single content block as a markdown fragment. Each fragment
 * is later joined by blank lines, so callers must not append leading or
 * trailing blank lines themselves.
 *
 * Image blocks use markdown images; video blocks use `<video>` with
 * responsive inline styles so they fill the article width like images in
 * prose layouts. Captions render as italic text on the line below so they
 * stay readable even in editors that do not parse `<figure>` tags.
 */
const serializeContentBlock = (block: ContentBlock): string => {
  if (block.type === 'paragraph') {
    return block.text.trim()
  }

  if (block.type === 'href') {
    return `[${block.label.trim()}](${block.href})`
  }

  if (block.type === 'heading') {
    const prefix = block.level === 4 ? '####' : '###'
    return `${prefix} ${block.text.trim()}`
  }

  if (block.type === 'list') {
    const marker = block.ordered ? (index: number): string => `${index + 1}.` : (): string => '-'
    return block.items.map((item, index) => `${marker(index)} ${item.trim()}`).join('\n')
  }

  if (block.type === 'image') {
    const image = `![${block.alt}](${block.src})`
    return block.caption ? `${image}\n\n_${block.caption.trim()}_` : image
  }

  if (block.type === 'video') {
    // Video block. Use the `<video>` HTML element so GitHub and most
    // documentation viewers render it inline. Width/height styles match
    // typical responsive `<img>` behaviour (full width of the column).
    // Poster, autoplay, loop, and muted mirror the JSON for parity with
    // the in-app modal.
    const attrs: string[] = [`src="${block.src}"`, 'style="max-width: 100%; width: 100%; height: auto;"']
    if (block.poster) {
      attrs.push(`poster="${block.poster}"`)
    }
    if (block.autoplay) {
      attrs.push('autoplay')
    }
    if (block.loop) {
      attrs.push('loop')
    }
    if (block.muted) {
      attrs.push('muted')
    }
    if (block.controls !== false) {
      attrs.push('controls')
    }
    attrs.push('playsinline')
    const video = `<video ${attrs.join(' ')}></video>`
    return block.caption ? `${video}\n\n_${block.caption.trim()}_` : video
  }

  const _exhaustive: never = block
  void _exhaustive
  return ''
}
