/**
 * Shared parser and serializer for the human-readable release-notes
 * markdown file (`RELEASE_NOTES.md`) used by the Scalar app's "What's
 * new" modal.
 *
 * The file is the single source of truth: the release-notes generator
 * appends to it on every release, and the app bundles it via Vite's
 * `?raw` import and parses it at module load. Keeping a small, dependency
 * free parser here means both producers and consumers share the same
 * format guarantees.
 *
 * Format (one entry per release, newest first):
 *
 * ```markdown
 * ## 3.5.1 (2026-04-25)
 *
 * ### Smoother request runs and a friendlier slugger
 *
 * A small follow-up to the 3.5.0 release ...
 *
 * - Pending edits are now flushed before a request runs.
 * - Switched to our own slug generator.
 *
 * [Read full release notes](https://github.com/scalar/scalar/releases/tag/%40scalar%2Fapi-client%403.5.1)
 * ```
 *
 * Anything before the first `## ` heading is treated as the file preamble
 * (title, comments, intro) and preserved on round-trip.
 */

/** Parsed release-note entry. Mirrors the Scalar app's `ReleaseNote` type. */
export type ReleaseNoteEntry = {
  /** Semver-style version string (for example `3.5.1`). */
  version: string
  /** Release date in `YYYY-MM-DD` format. */
  date: string
  /** Short, sentence-case headline. */
  title: string
  /** Optional one-paragraph summary (paragraphs joined with two newlines). */
  description?: string
  /** Optional bullet list of single-sentence highlights. */
  highlights?: string[]
  /** Optional URL for the "Read full release notes" link. */
  href?: string
}

/**
 * Default file preamble. Used by `serializeReleaseNotes` when no preamble
 * is supplied so the generator never accidentally writes a headerless file.
 */
export const DEFAULT_RELEASE_NOTES_PREAMBLE = `# Release notes

<!--
  Auto-generated by \`tooling/release-notes-generator\` on every release.
  Newest entries on top. Bundled with the package and read at runtime by
  the "What's new" modal in the Scalar app - keep the format stable.
-->
`

const VERSION_HEADING_PATTERN = /^##\s+(\S+)\s*\(\s*(\d{4}-\d{2}-\d{2})\s*\)\s*$/
const TITLE_HEADING_PATTERN = /^###\s+(.+?)\s*$/
const HIGHLIGHT_PATTERN = /^[-*]\s+(.+?)\s*$/
const LINK_LINE_PATTERN = /^\[[^\]]+\]\(([^)]+)\)\s*$/

/**
 * Parse a `RELEASE_NOTES.md` document into structured entries. Sections
 * that do not match the expected shape are skipped silently so a single
 * malformed entry never breaks the entire modal.
 */
export const parseReleaseNotes = (markdown: string): ReleaseNoteEntry[] => {
  const lines = markdown.split(/\r?\n/)
  const entries: ReleaseNoteEntry[] = []

  let cursor = 0
  // Skip the preamble - everything before the first version heading.
  while (cursor < lines.length && !VERSION_HEADING_PATTERN.test(lines[cursor] ?? '')) {
    cursor += 1
  }

  while (cursor < lines.length) {
    const headingMatch = VERSION_HEADING_PATTERN.exec(lines[cursor] ?? '')
    if (!headingMatch) {
      cursor += 1
      continue
    }
    const version = headingMatch[1] ?? ''
    const date = headingMatch[2] ?? ''
    cursor += 1

    // Find the end of this entry (next `## ` heading or end of file).
    let sectionEnd = cursor
    while (sectionEnd < lines.length && !/^##\s/.test(lines[sectionEnd] ?? '')) {
      sectionEnd += 1
    }
    const sectionLines = lines.slice(cursor, sectionEnd)
    cursor = sectionEnd

    const entry = parseSection(version, date, sectionLines)
    if (entry) {
      entries.push(entry)
    }
  }

  return entries
}

/**
 * Parse the body lines for a single release entry. Returns `null` when the
 * section is missing required fields (version, date, title) so the caller
 * can skip it without raising.
 */
const parseSection = (version: string, date: string, sectionLines: string[]): ReleaseNoteEntry | null => {
  if (!version || !date) {
    return null
  }

  let index = 0

  // Skip blank lines after the version heading.
  while (index < sectionLines.length && (sectionLines[index] ?? '').trim() === '') {
    index += 1
  }

  const titleMatch = TITLE_HEADING_PATTERN.exec(sectionLines[index] ?? '')
  if (!titleMatch?.[1]) {
    return null
  }
  const title = titleMatch[1]
  index += 1

  const descriptionParagraphs: string[] = []
  const highlights: string[] = []
  let href: string | undefined
  let currentParagraph: string[] = []

  const flushParagraph = (): void => {
    if (currentParagraph.length === 0) {
      return
    }
    const paragraph = currentParagraph.join(' ').trim()
    if (paragraph.length > 0 && highlights.length === 0) {
      // Only collect paragraphs as `description` when they appear before
      // the highlight list. Anything after the bullets is either the
      // trailing link line or formatting noise.
      descriptionParagraphs.push(paragraph)
    }
    currentParagraph = []
  }

  for (; index < sectionLines.length; index += 1) {
    const line = sectionLines[index] ?? ''
    const trimmed = line.trim()

    if (trimmed === '') {
      flushParagraph()
      continue
    }

    const linkMatch = LINK_LINE_PATTERN.exec(trimmed)
    if (linkMatch?.[1]) {
      flushParagraph()
      href = linkMatch[1]
      continue
    }

    const highlightMatch = HIGHLIGHT_PATTERN.exec(trimmed)
    if (highlightMatch?.[1]) {
      flushParagraph()
      highlights.push(highlightMatch[1])
      continue
    }

    currentParagraph.push(trimmed)
  }
  flushParagraph()

  return {
    version,
    date,
    title,
    ...(descriptionParagraphs.length > 0 ? { description: descriptionParagraphs.join('\n\n') } : {}),
    ...(highlights.length > 0 ? { highlights } : {}),
    ...(href ? { href } : {}),
  }
}

/**
 * Serialize a list of entries back into a `RELEASE_NOTES.md` document.
 * Entries are emitted in the order provided - callers should sort newest
 * first before calling this function.
 *
 * The output is deterministic so a `parseReleaseNotes` -> `serializeReleaseNotes`
 * round-trip on a generator-written file is a no-op.
 */
export const serializeReleaseNotes = (entries: ReleaseNoteEntry[], options: { preamble?: string } = {}): string => {
  const preamble = options.preamble ?? DEFAULT_RELEASE_NOTES_PREAMBLE
  const sections = entries.map(serializeEntry)
  const body = sections.join('\n')

  // Always end with a single trailing newline so the file plays nicely
  // with text-editing tools and POSIX expectations.
  const preambleBlock = preamble.replace(/\s+$/, '')
  return `${preambleBlock}\n\n${body.trimEnd()}\n`
}

const serializeEntry = (entry: ReleaseNoteEntry): string => {
  const blocks: string[] = []
  blocks.push(`## ${entry.version} (${entry.date})`)
  blocks.push(`### ${entry.title}`)
  if (entry.description && entry.description.trim().length > 0) {
    blocks.push(entry.description.trim())
  }
  if (entry.highlights && entry.highlights.length > 0) {
    blocks.push(entry.highlights.map((highlight) => `- ${highlight.trim()}`).join('\n'))
  }
  if (entry.href) {
    blocks.push(`[Read full release notes](${entry.href})`)
  }
  return `${blocks.join('\n\n')}\n`
}
