/**
 * Serialize curated release notes into the human-readable `RELEASE_NOTES.md`
 * shape used as a derived view next to `RELEASE_NOTES.json`.
 *
 * The Scalar app's "What's new" modal reads structured data from JSON at
 * build time; this module exists so the release-notes generator can still
 * emit a markdown file for humans browsing the repo without maintaining a
 * second hand-written format.
 *
 * Format (one entry per release, caller supplies order — newest first):
 *
 * ```markdown
 * ## 3.5.1 (2026-04-25)
 *
 * ### Smoother request runs and a friendlier slugger
 *
 * A small follow-up to the 3.5.0 release ...
 *
 * - Pending edits are now flushed before a request runs.
 * - Switched to our own slug generator.
 *
 * [Read full release notes](https://github.com/scalar/scalar/releases/tag/%40scalar%2Fapi-client%403.5.1)
 * ```
 *
 * Anything before the first `## ` heading is the preamble (passed in via
 * `serializeReleaseNotes` options or defaulted).
 */

/** One release note row. Mirrors the Scalar app's `ReleaseNote` shape. */
export type ReleaseNoteEntry = {
  /** Semver-style version string (for example `3.5.1`). */
  version: string
  /** Release date in `YYYY-MM-DD` format. */
  date: string
  /** Short, sentence-case headline. */
  title: string
  /** Optional one-paragraph summary (paragraphs joined with two newlines). */
  description?: string
  /** Optional bullet list of single-sentence highlights. */
  highlights?: string[]
  /** Optional URL for the "Read full release notes" link. */
  href?: string
}

/**
 * Default file preamble. Used by `serializeReleaseNotes` when no preamble
 * is supplied so the generator never accidentally writes a headerless file.
 *
 * The accompanying `RELEASE_NOTES.json` is the source of truth - this
 * markdown file is a human-friendly view that gets regenerated on every
 * release. Edits made directly to the markdown will be overwritten.
 */
export const DEFAULT_RELEASE_NOTES_PREAMBLE = `# Release notes

<!--
  Auto-generated by the \`release-notes-generator\` command in
  \`tooling/scripts\` on every release. Newest entries on top.

  Source of truth: \`RELEASE_NOTES.json\` next to this file. The Scalar
  app's "What's new" modal imports the JSON directly; this markdown file
  is a derived, human-friendly view that gets regenerated on every
  release - edits made directly here will be overwritten.
-->
`

/**
 * Serialize a list of entries into a `RELEASE_NOTES.md` document.
 * Entries are emitted in the order provided - callers should sort newest
 * first before calling this function.
 *
 * The output is deterministic for a given preamble and entry list.
 */
export const serializeReleaseNotes = (entries: ReleaseNoteEntry[], options: { preamble?: string } = {}): string => {
  const preamble = options.preamble ?? DEFAULT_RELEASE_NOTES_PREAMBLE
  const sections = entries.map(serializeEntry)
  const body = sections.join('\n')

  // Always end with a single trailing newline so the file plays nicely
  // with text-editing tools and POSIX expectations.
  const preambleBlock = preamble.replace(/\s+$/, '')
  return `${preambleBlock}\n\n${body.trimEnd()}\n`
}

const serializeEntry = (entry: ReleaseNoteEntry): string => {
  const blocks: string[] = []
  blocks.push(`## ${entry.version} (${entry.date})`)
  blocks.push(`### ${entry.title}`)
  if (entry.description && entry.description.trim().length > 0) {
    blocks.push(entry.description.trim())
  }
  if (entry.highlights && entry.highlights.length > 0) {
    blocks.push(entry.highlights.map((highlight) => `- ${highlight.trim()}`).join('\n'))
  }
  if (entry.href) {
    blocks.push(`[Read full release notes](${entry.href})`)
  }
  return `${blocks.join('\n\n')}\n`
}
