//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Scalar ASP.NET Core enum generator.
//     Source: /packages/snippetz/src/clients.ts
//     Command: pnpm generate:enums
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Text.Json.Serialization;
using NetEscapades.EnumGenerators;

namespace Scalar.AspNetCore;

/// <summary>
/// Represents the different clients available in Scalar.
/// This enum is auto-generated from TypeScript clients configuration.
/// </summary>
[EnumExtensions]
[JsonConverter(typeof(ScalarClientJsonConverter))]
public enum ScalarClient
{
    /// <summary>
    /// Libcurl client.
    /// </summary>
    [Description("libcurl")]
    Libcurl,

    /// <summary>
    /// HttpClient client.
    /// </summary>
    [Description("httpclient")]
    HttpClient,

    /// <summary>
    /// RestSharp client.
    /// </summary>
    [Description("restsharp")]
    RestSharp,

    /// <summary>
    /// clj-http client.
    /// </summary>
    [Description("clj_http")]
    CljHttp,

    /// <summary>
    /// Http client.
    /// </summary>
    [Description("http")]
    Http,

    /// <summary>
    /// net::http client.
    /// </summary>
    [Description("native")]
    Native,

    /// <summary>
    /// HTTP/1.1 client.
    /// </summary>
    [Description("http1.1")]
    Http11,

    /// <summary>
    /// AsyncHttp client.
    /// </summary>
    [Description("asynchttp")]
    AsyncHttp,

    /// <summary>
    /// java.net.http client.
    /// </summary>
    [Description("nethttp")]
    NetHttp,

    /// <summary>
    /// OkHttp client.
    /// </summary>
    [Description("okhttp")]
    OkHttp,

    /// <summary>
    /// Unirest client.
    /// </summary>
    [Description("unirest")]
    Unirest,

    /// <summary>
    /// Fetch client.
    /// </summary>
    [Description("fetch")]
    Fetch,

    /// <summary>
    /// Axios client.
    /// </summary>
    [Description("axios")]
    Axios,

    /// <summary>
    /// ofetch client.
    /// </summary>
    [Description("ofetch")]
    OFetch,

    /// <summary>
    /// jQuery client.
    /// </summary>
    [Description("jquery")]
    JQuery,

    /// <summary>
    /// XHR client.
    /// </summary>
    [Description("xhr")]
    Xhr,

    /// <summary>
    /// undici client.
    /// </summary>
    [Description("undici")]
    Undici,

    /// <summary>
    /// NSURLSession client.
    /// </summary>
    [Description("nsurlsession")]
    NSUrlSession,

    /// <summary>
    /// Cohttp client.
    /// </summary>
    [Description("cohttp")]
    CoHttp,

    /// <summary>
    /// Curl client.
    /// </summary>
    [Description("curl")]
    Curl,

    /// <summary>
    /// Guzzle client.
    /// </summary>
    [Description("guzzle")]
    Guzzle,

    /// <summary>
    /// Invoke-WebRequest client.
    /// </summary>
    [Description("webrequest")]
    WebRequest,

    /// <summary>
    /// Invoke-RestMethod client.
    /// </summary>
    [Description("restmethod")]
    RestMethod,

    /// <summary>
    /// http.client client.
    /// </summary>
    [Description("python3")]
    Python3,

    /// <summary>
    /// Requests client.
    /// </summary>
    [Description("requests")]
    Requests,

    /// <summary>
    /// HTTPX (Sync) client.
    /// </summary>
    [Description("httpx_sync")]
    HttpxSync,

    /// <summary>
    /// HTTPX (Async) client.
    /// </summary>
    [Description("httpx_async")]
    HttpxAsync,

    /// <summary>
    /// httr client.
    /// </summary>
    [Description("httr")]
    Httr,

    /// <summary>
    /// reqwest client.
    /// </summary>
    [Description("reqwest")]
    Reqwest,

    /// <summary>
    /// Wget client.
    /// </summary>
    [Description("wget")]
    Wget,

    /// <summary>
    /// HTTPie client.
    /// </summary>
    [Description("httpie")]
    Httpie,

    /// <summary>
    /// Use NSUrlSession instead.
    /// </summary>
    [Obsolete("Use NSUrlSession instead.")]
    [Description("nsurlsession")]
    Nsurlsession,

    /// <summary>
    /// This client is no longer supported.
    /// </summary>
    [Obsolete("This client is no longer supported.")]
    [Description("http1")]
    Http1,

    /// <summary>
    /// This client is no longer supported.
    /// </summary>
    [Obsolete("This client is no longer supported.")]
    [Description("http2")]
    Http2,
}