//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Scalar ASP.NET Core enum generator.
//     Source: /packages/snippetz/src/clients.ts
//     Command: pnpm generate:enums
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Text.Json.Serialization;
using NetEscapades.EnumGenerators;

namespace Scalar.AspNetCore;

/// <summary>
/// Represents the different targets available in Scalar.
/// </summary>
[EnumExtensions]
[JsonConverter(typeof(ScalarTargetJsonConverter))]
public enum ScalarTarget
{
    /// <summary>
    /// C.
    /// </summary>
    [Description("c")]
    C,

    /// <summary>
    /// Clojure.
    /// </summary>
    [Description("clojure")]
    Clojure,

    /// <summary>
    /// C#.
    /// </summary>
    [Description("csharp")]
    CSharp,

    /// <summary>
    /// Dart.
    /// </summary>
    [Description("dart")]
    Dart,

    /// <summary>
    /// Go.
    /// </summary>
    [Description("go")]
    Go,

    /// <summary>
    /// HTTP.
    /// </summary>
    [Description("http")]
    Http,

    /// <summary>
    /// Java.
    /// </summary>
    [Description("java")]
    Java,

    /// <summary>
    /// JavaScript.
    /// </summary>
    [Description("js")]
    JavaScript,

    /// <summary>
    /// Kotlin.
    /// </summary>
    [Description("kotlin")]
    Kotlin,

    /// <summary>
    /// Node.js.
    /// </summary>
    [Description("node")]
    Node,

    /// <summary>
    /// Objective-C.
    /// </summary>
    [Description("objc")]
    ObjC,

    /// <summary>
    /// OCaml.
    /// </summary>
    [Description("ocaml")]
    OCaml,

    /// <summary>
    /// PHP.
    /// </summary>
    [Description("php")]
    Php,

    /// <summary>
    /// PowerShell.
    /// </summary>
    [Description("powershell")]
    PowerShell,

    /// <summary>
    /// Python.
    /// </summary>
    [Description("python")]
    Python,

    /// <summary>
    /// R.
    /// </summary>
    [Description("r")]
    R,

    /// <summary>
    /// Ruby.
    /// </summary>
    [Description("ruby")]
    Ruby,

    /// <summary>
    /// Rust.
    /// </summary>
    [Description("rust")]
    Rust,

    /// <summary>
    /// Shell.
    /// </summary>
    [Description("shell")]
    Shell,

    /// <summary>
    /// Swift.
    /// </summary>
    [Description("swift")]
    Swift,
}