//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Scalar ASP.NET Core enum generator.
//     Source: /packages/snippetz/src/clients.ts
//     Command: pnpm generate:enums
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Text.Json.Serialization;
using NetEscapades.EnumGenerators;

namespace Scalar.AspNetCore;

/// <summary>
/// Represents the different targets available in Scalar.
/// </summary>
[EnumExtensions]
[JsonConverter(typeof(ScalarTargetJsonConverter))]
public enum ScalarTarget
{
    /// <summary>
    /// C programming language.
    /// </summary>
    [Description("c")]
    C,

    /// <summary>
    /// C# programming language.
    /// </summary>
    [Description("csharp")]
    CSharp,

    /// <summary>
    /// Clojure programming language.
    /// </summary>
    [Description("clojure")]
    Clojure,

    /// <summary>
    /// Dart programming language.
    /// </summary>
    [Description("dart")]
    Dart,

    /// <summary>
    /// Go programming language.
    /// </summary>
    [Description("go")]
    Go,

    /// <summary>
    /// HTTP programming language.
    /// </summary>
    [Description("http")]
    Http,

    /// <summary>
    /// Java programming language.
    /// </summary>
    [Description("java")]
    Java,

    /// <summary>
    /// JavaScript programming language.
    /// </summary>
    [Description("js")]
    JavaScript,

    /// <summary>
    /// Kotlin programming language.
    /// </summary>
    [Description("kotlin")]
    Kotlin,

    /// <summary>
    /// Node.js programming language.
    /// </summary>
    [Description("node")]
    Node,

    /// <summary>
    /// Objective-C programming language.
    /// </summary>
    [Description("objc")]
    ObjC,

    /// <summary>
    /// OCaml programming language.
    /// </summary>
    [Description("ocaml")]
    OCaml,

    /// <summary>
    /// PHP programming language.
    /// </summary>
    [Description("php")]
    Php,

    /// <summary>
    /// Powershell programming language.
    /// </summary>
    [Description("powershell")]
    PowerShell,

    /// <summary>
    /// Python programming language.
    /// </summary>
    [Description("python")]
    Python,

    /// <summary>
    /// R programming language.
    /// </summary>
    [Description("r")]
    R,

    /// <summary>
    /// Ruby programming language.
    /// </summary>
    [Description("ruby")]
    Ruby,

    /// <summary>
    /// Rust programming language.
    /// </summary>
    [Description("rust")]
    Rust,

    /// <summary>
    /// Shell programming language.
    /// </summary>
    [Description("shell")]
    Shell,

    /// <summary>
    /// Swift programming language.
    /// </summary>
    [Description("swift")]
    Swift,
}