import type { PartialDeep } from 'type-fest'

/** Some common properties used in all security schemes */
type SecuirtySchemeCommon = {
  /* A description for security scheme. CommonMark syntax MAY be used for rich text representation. */
  description: string | undefined
}

// Apikey
type ExtendedSecurityScheme = {
  uid: any
  /** The name key that links a security requirement to a security object */
  nameKey: string
}

type SecuritySchemeApiKeyIn = 'query' | 'header' | 'cookie'

type OasSecurityApiKey = {
  type: 'apiKey'
  /** REQUIRED. The name of the header, query or cookie parameter to be used. */
  name: string
  /** REQUIRED. The location of the API key. Valid values are "query", "header" or "cookie". */
  in: SecuritySchemeApiKeyIn
  /** REQUIRED. The API key to be sent in the Authorization header or as a cookie. */
  value: string
}

export type SecuritySchemeApiKey = SecuirtySchemeCommon & ExtendedSecurityScheme & OasSecurityApiKey

// HTTP
type OasSecurityHttp = {
  type: 'http'
  /** REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in
   * [RFC7235]. The values used SHOULD be registered in the IANA Authentication Scheme registry. */
  scheme: 'basic' | 'bearer'
  /** A hint to the client to identify how the bearer token is formatted.
   * Bearer tokens are usually generated by an authorization server, so
   * this information is primarily for documentation purposes. */
  bearerFormat: 'JWT' | string
  /** The username to be sent in the Authorization header. */
  username: string
  /** The password to be sent in the Authorization header. */
  password: string
  /** The token to be sent in the Authorization header. */
  token: string
}

export type SecuritySchemeHttp = SecuirtySchemeCommon & ExtendedSecurityScheme & OasSecurityHttp

// OPENID CONNECT

type OasSecurityOpenIdConnect = {
  type: 'openIdConnect'
  /** REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the
   * form of a URL. The OpenID Connect standard requires the use of TLS. */
  openIdConnectUrl: string
}
export type SecuritySchemeOpenIdConnect = SecuirtySchemeCommon & ExtendedSecurityScheme & OasSecurityOpenIdConnect

// OAUTH2

type FlowsCommon = {
  /**
   * The URL to be used for obtaining refresh tokens. This MUST be in the form of a
   * URL. The OAuth2 standard requires the use of TLS.
   */
  'refreshUrl'?: string
  /**
   * REQUIRED. The available scopes for the OAuth2 security scheme. A map
   * between the scope name and a short description for it. The map MAY be empty.
   */
  'scopes'?: Record<string, string>
  'selectedScopes'?: string[]
  /** Extension to save the client Id associated with an oauth flow */
  'x-scalar-client-id'?: string
  /** The auth token */
  'token'?: string
  /** Additional query parameters for the OAuth authorization request. Example: { prompt: 'consent', audience: 'scalar' }. */
  'x-scalar-security-query'?: Record<string, string>
  /** Additional body parameters for the OAuth token request. Example: { audience: 'foo' }. */
  'x-scalar-security-body'?: Record<string, string>
  /** Extension to specify custom token name in the response (defaults to 'access_token') */
  'x-tokenName'?: string
}

type PkceOptions = 'SHA-256' | 'plain' | 'no'

/** Allowed values for the OAuth2 `x-usePkce` extension */
export const pkceOptions = ['SHA-256', 'plain', 'no'] as const satisfies readonly PkceOptions[]

type CredentialsLocationExtension = 'header' | 'body'

type OasSecurityOauth2FlowImplicit = {
  type: 'oauth2'
  'x-default-scopes'?: string[]
  flows: {
    implicit: FlowsCommon & {
      type: 'implicit'
      authorizationUrl: string
      'x-scalar-redirect-uri'?: string
    }
    password: FlowsCommon & {
      type: 'password'
      tokenUrl: string
      clientSecret: string
      username: string
      password: string
      'x-scalar-credentials-location'?: CredentialsLocationExtension
    }
    clientCredentials: FlowsCommon & {
      type: 'clientCredentials'
      tokenUrl: string
      clientSecret: string
      'x-scalar-credentials-location'?: CredentialsLocationExtension
    }
    authorizationCode: FlowsCommon & {
      type: 'authorizationCode'
      authorizationUrl: string
      tokenUrl: string
      clientSecret: string
      'x-scalar-credentials-location'?: CredentialsLocationExtension
      'x-usePkce'?: PkceOptions
      'x-scalar-redirect-uri'?: string
    }
  }
}

export type SecuritySchemeOauth2 = SecuirtySchemeCommon & ExtendedSecurityScheme & OasSecurityOauth2FlowImplicit

/** One configured OAuth2 flow (implicit, password, client credentials, or authorization code) */
export type Oauth2Flow = NonNullable<
  SecuritySchemeOauth2['flows']['authorizationCode' | 'clientCredentials' | 'implicit' | 'password']
>

/** OAuth2 security scheme before runtime defaults (legacy compatibility alias) */
export type SecuritySchemeOauth2Payload = SecuritySchemeOauth2

/** Single-flow payload shape (legacy compatibility alias) */
export type Oauth2FlowPayload = NonNullable<SecuritySchemeOauth2Payload['flows']>[
  | 'authorizationCode'
  | 'clientCredentials'
  | 'implicit'
  | 'password'] &
  Record<`x-${string}`, string>

/** Union of security schemes before runtime defaults (legacy compatibility alias) */
export type SecuritySchemePayload = SecurityScheme

// Union of all security schemes
export type SecurityScheme =
  | SecuritySchemeApiKey
  | SecuritySchemeHttp
  | SecuritySchemeOpenIdConnect
  | SecuritySchemeOauth2

/**
 * Authentication configuration for the API reference.
 */
export type AuthenticationConfiguration = {
  /**
   * Specifies the preferred security scheme(s) to use for authentication.
   * Can be one of:
   * - A single security scheme name (string)
   * - An array of security scheme names (OR relationship)
   * - An array containing strings or arrays of strings (AND/OR relationship)
   */
  preferredSecurityScheme?: string | (string | string[])[] | null

  /**
   * Setting security schemes this way will allow you to override any value in your openapi document
   * You will also be able to set additional values such as api tokens etc.
   *
   * Set them via the nameKey in your components.securitySchemes.[nameKey]
   *
   * @example
   * ```ts
   * {
   *   authentication: {
   *     preferredSecurityScheme: 'apiKeyHeader',
   *     securitySchemes: {
   *       apiKeyHeader: {
   *         value: 'tokenValue'
   *       },
   *       httpBearer: {
   *         token: 'xyz token value'
   *       },
   *       httpBasic: {
   *         username: 'username',
   *         password: 'password'
   *       },
   *       oauth2: {
   *         flows: {
   *           authorizationCode: {
   *             token: 'auth code token'
   *           }
   *         }
   *       },
   *     },
   *   }
   * }
   * ```
   *
   */
  securitySchemes?: Record<string, PartialDeep<SecurityScheme>>
  /**
   * Allows adding authentication which is not in the document.
   * When true, generic options (API Key, HTTP Basic, OAuth2, etc.) are shown in the auth dropdown.
   * @default false
   */
  createAnySecurityScheme?: boolean
}
