<script setup lang="ts">
import {
  DataTable,
  DataTableHeader,
  DataTableRow,
} from '@/components/DataTable'
import DataTableCell from '@/components/DataTable/DataTableCell.vue'
import ViewLayoutCollapse from '@/components/ViewLayout/ViewLayoutCollapse.vue'
import { type UpdateScheme, useWorkspace } from '@/store/workspace'
import RequestAuthDataTableInput from '@/views/Request/RequestSection/RequestAuthDataTableInput.vue'
import { OAuth2 } from '@/views/Request/components'
import {
  ADD_AUTH_DICT,
  ADD_AUTH_OPTIONS,
  type SecuritySchemeGroup,
  type SecuritySchemeOption,
} from '@/views/Request/consts'
import {
  ScalarButton,
  ScalarComboboxMultiselect,
  ScalarIcon,
} from '@scalar/components'
import type { SecurityScheme } from '@scalar/oas-utils/entities/workspace/security'
import { camelToTitleWords } from '@scalar/oas-utils/helpers'
import { capitalize, computed, ref } from 'vue'

defineProps<{
  title: string
}>()

const {
  activeCollection,
  activeRequest,
  activeSecurityRequirements,
  activeSecuritySchemes,
  isReadOnly,
  requestMutators,
  securitySchemeMutators,
  securitySchemes,
} = useWorkspace()

const comboboxRef = ref<typeof ScalarComboboxMultiselect | null>(null)

/** Something to split the string by that won't be generated by uid */
const MULTI_AUTH_DELIMITER = '*sclrMulti*'

/** Generate pretty name for the dropdown label */
const getLabel = (scheme: SecurityScheme) => {
  switch (scheme?.type) {
    case 'apiKey':
      return `${capitalize(scheme.in)}`
    case 'http': {
      return `${capitalize(scheme.scheme)} Authentication`
    }
    case 'oauth2':
      return camelToTitleWords(scheme.flow.type)
    case 'openIdConnect':
      return `Open ID Connect`
    default:
      return 'None'
  }
}

/** Generate the options for the dropdown */
const schemeOptions = computed<SecuritySchemeOption[] | SecuritySchemeGroup[]>(
  () => {
    const securitySchemesDict = activeCollection.value?.securitySchemeDict

    /** Security options from the spec */
    const specOptions = activeSecurityRequirements.value.flatMap((req) => {
      const keys = Object.keys(req)

      // Optional
      if (keys.length === 0 && isReadOnly.value)
        return { id: 'none', label: 'None' }

      if (!securitySchemesDict) return []

      // Multi Auth combined into one option
      if (keys.length > 1) {
        const schemes = keys.map((key) => {
          const id = securitySchemesDict[key]
          const scheme = securitySchemes[id]
          return scheme
        })
        const label = schemes.map((scheme) => scheme.nameKey).join(' & ')

        return {
          id:
            MULTI_AUTH_DELIMITER +
            schemes.map((scheme) => scheme.uid).join(MULTI_AUTH_DELIMITER),
          label,
        }
      }

      // Active requirements
      return keys.flatMap((key) => {
        const id = securitySchemesDict[key]
        const scheme = securitySchemes[id]
        const label = getLabel(scheme)

        return {
          id,
          label,
        }
      })
    })

    // For the modal we only provide available auth
    if (isReadOnly.value) {
      return specOptions
    }
    // For the client app we provide all options
    else {
      const options = activeRequest.value.securitySchemeUids.map((uid) => {
        const scheme = securitySchemes[uid]
        const label = getLabel(scheme)

        return {
          id: uid,
          label:
            'name' in scheme && scheme.name.length
              ? `${label} (${scheme.name})`
              : label,
        }
      })

      /** Filter out when an auth option get unchecked */
      const selectedUids = activeRequest.value.selectedSecuritySchemeUids
      const filteredOptions = options.filter((option) =>
        selectedUids.includes(option.id),
      )

      return [
        { label: 'Select auth', options: [...specOptions, ...filteredOptions] },
        {
          label: 'Add new auth',
          options: ADD_AUTH_OPTIONS,
        },
      ] as const
    }
  },
)

/** Splits up a multi auth ID by delimiter and returns an array of IDs */
const splitMultiAuth = (id: string) => {
  if (id.startsWith(MULTI_AUTH_DELIMITER)) {
    const ids = id.split(MULTI_AUTH_DELIMITER)
    ids.shift()
    return ids
  } else {
    return [id]
  }
}

const selectedAuth = computed({
  // Grab the selected OR first security scheme
  get: () => {
    // Create a Set of selected security scheme UIDs for fast lookup
    const selectedSchemeUids = new Set(
      activeRequest.value?.selectedSecuritySchemeUids || [],
    )

    // Return all schemes selected on this request
    return schemeOptions.value
      .flatMap((schemeOption) =>
        'options' in schemeOption ? schemeOption.options : schemeOption,
      )
      .filter((scheme) =>
        splitMultiAuth(scheme.id).some((id) => selectedSchemeUids.has(id)),
      )
  },

  // Update the selected auth per this request
  set: (options) => {
    const newAuthOption = options.find(
      (val) => ADD_AUTH_DICT[val.id as keyof typeof ADD_AUTH_DICT],
    )

    // Add new auth
    if (newAuthOption?.payload && activeCollection.value) {
      // Closing the popup as we don't want to keep selecting
      comboboxRef.value?.comboboxPopoverRef?.popoverButtonRef?.el?.click()

      securitySchemeMutators.add(
        newAuthOption.payload,
        activeCollection.value.uid,
        activeRequest.value,
        true,
      )
    }
    // Select existing auth
    else {
      requestMutators.edit(
        activeRequest.value.uid,
        'selectedSecuritySchemeUids',
        options.flatMap((opt) => splitMultiAuth(opt.id)),
      )
    }
  },
})

/** Get labels for the scheme, handles multi auth */
const labels = computed(() =>
  selectedAuth.value
    .flatMap(({ id }) => splitMultiAuth(id))
    .map((id) => {
      const scheme = securitySchemes[id]
      return `${getLabel(scheme)} (${scheme.nameKey})`
    }),
)

type UpdateSchemeParams = Parameters<UpdateScheme>

/** Update the selected scheme */
const updateScheme = (
  scheme: SecurityScheme,
  path: UpdateSchemeParams[0],
  value: UpdateSchemeParams[1],
) => securitySchemeMutators.edit(scheme.uid ?? '', path, value)

const unselectAuth = (id: string) => {
  const updatedSelectedAuth = selectedAuth.value.filter(
    (auth: SecuritySchemeOption) => auth.id !== id,
  )
  selectedAuth.value = updatedSelectedAuth
}
</script>
<template>
  <ViewLayoutCollapse
    class="group/params"
    :itemCount="selectedAuth.length">
    <template #title>
      <div class="flex gap-1">
        {{ title }}
      </div>
    </template>
    <form>
      <DataTable
        class="flex-1"
        :columns="['']">
        <DataTableRow>
          <DataTableHeader
            class="relative col-span-full cursor-pointer py-[0px] px-[0px] flex items-center">
            <ScalarComboboxMultiselect
              ref="comboboxRef"
              v-model="selectedAuth"
              class="text-xs w-full"
              fullWidth
              multiple
              :options="schemeOptions"
              style="margin-left: 120px"
              teleport>
              <ScalarButton
                class="h-auto py-0 px-0 text-c-2 hover:text-c-1 font-normal justify-start"
                fullWidth
                variant="ghost">
                <div
                  class="text-c-2 h-8 flex min-w-[120px] items-center border-r-1/2 pr-0 pl-2">
                  Auth Type
                </div>
                <div
                  v-if="selectedAuth.length"
                  class="flex relative scroll-timeline-x w-full">
                  <div class="fade-left"></div>
                  <div class="flex flex-1 gap-0.75 mr-1.5 items-center pl-0.5">
                    <span
                      v-for="auth in selectedAuth"
                      :key="auth.id"
                      class="cm-pill flex items-center mx-0 h-fit">
                      {{ auth.label }}
                      <ScalarIcon
                        class="ml-1 cursor-pointer text-c-3 hover:text-c-1"
                        icon="Close"
                        size="xs"
                        @click.stop="unselectAuth(auth.id)" />
                    </span>
                  </div>
                  <div class="fade-right"></div>
                </div>
                <div
                  v-else
                  class="pl-2">
                  None
                </div>
                <ScalarIcon
                  class="min-w-3 ml-auto mr-2.5"
                  icon="ChevronDown"
                  size="xs" />
              </ScalarButton>
            </ScalarComboboxMultiselect>
          </DataTableHeader>
        </DataTableRow>

        <!-- Loop over for multiple auth selection -->
        <template
          v-for="(scheme, index) in activeSecuritySchemes"
          :key="scheme.uid">
          <!-- Header -->
          <DataTableRow
            v-if="activeSecuritySchemes.length > 1"
            class="group/delete">
            <DataTableCell
              class="text-c-2 pl-2 text-xs font-medium flex items-center bg-b-2">
              {{ labels[index] }}
            </DataTableCell>
          </DataTableRow>

          <!-- HTTP -->
          <template v-if="scheme.type === 'http'">
            <!-- Bearer -->
            <DataTableRow v-if="scheme.scheme === 'bearer'">
              <RequestAuthDataTableInput
                :id="`http-bearer-token-${scheme.uid}`"
                :modelValue="scheme.value"
                placeholder="Token"
                type="password"
                @update:modelValue="(v) => updateScheme(scheme, 'value', v)">
                Bearer Token
              </RequestAuthDataTableInput>
            </DataTableRow>

            <!-- HTTP Basic -->
            <template v-else-if="scheme.scheme === 'basic'">
              <DataTableRow>
                <RequestAuthDataTableInput
                  :id="`http-basic-username-${scheme.uid}`"
                  class="text-c-2"
                  :modelValue="scheme.value"
                  placeholder="ScalarEnjoyer01"
                  required
                  @update:modelValue="(v) => updateScheme(scheme, 'value', v)">
                  Username
                </RequestAuthDataTableInput>
              </DataTableRow>
              <DataTableRow>
                <RequestAuthDataTableInput
                  :id="`http-basic-password-${scheme.uid}`"
                  :modelValue="scheme.secondValue"
                  placeholder="xxxxxx"
                  type="password"
                  @update:modelValue="
                    (v) => updateScheme(scheme, 'secondValue', v)
                  ">
                  Password
                </RequestAuthDataTableInput>
              </DataTableRow>
            </template>
          </template>

          <!-- API Key -->
          <template v-else-if="scheme.type === 'apiKey'">
            <!-- Custom auth -->
            <template v-if="!isReadOnly">
              <DataTableRow>
                <RequestAuthDataTableInput
                  :id="`api-key-name-${scheme.uid}`"
                  :modelValue="scheme.name"
                  placeholder="api-key"
                  @update:modelValue="(v) => updateScheme(scheme, 'name', v)">
                  Name
                </RequestAuthDataTableInput>
              </DataTableRow>
              <DataTableRow>
                <RequestAuthDataTableInput
                  :id="`api-key-value-add-${scheme.uid}`"
                  :modelValue="scheme.value"
                  placeholder="QUxMIFlPVVIgQkFTRSBBUkUgQkVMT05HIFRPIFVT"
                  @update:modelValue="(v) => updateScheme(scheme, 'value', v)">
                  Value
                </RequestAuthDataTableInput>
              </DataTableRow>
            </template>

            <DataTableRow v-else>
              <RequestAuthDataTableInput
                :id="`api-key-value-${scheme.uid}`"
                :modelValue="scheme.value"
                placeholder="Value"
                @update:modelValue="(v) => updateScheme(scheme, 'value', v)">
                {{ scheme.name }}
              </RequestAuthDataTableInput>
            </DataTableRow>
          </template>

          <!-- OAuth 2 -->
          <OAuth2
            v-else-if="scheme.type === 'oauth2'"
            :scheme="scheme" />
        </template>
      </DataTable>
    </form>
  </ViewLayoutCollapse>
</template>
<style scoped>
.auth-combobox-position {
  margin-left: 120px;
}
.scroll-timeline-x {
  overflow: auto;
  scroll-timeline: --scroll-timeline x;
  /* Firefox supports */
  scroll-timeline: --scroll-timeline horizontal;
  -ms-overflow-style: none; /* IE and Edge */
  scrollbar-width: none;
  -ms-overflow-style: none;
}
.fade-left,
.fade-right {
  position: sticky;
  content: '';
  height: 100%;
  animation-name: fadein;
  animation-duration: 1ms;
  animation-direction: reverse;
  animation-timeline: --scroll-timeline;
  min-height: 24px;
  pointer-events: none;
  z-index: 1;
}
.fade-left {
  background: linear-gradient(
    -90deg,
    color-mix(in srgb, var(--scalar-background-1), transparent 100%) 0%,
    color-mix(in srgb, var(--scalar-background-1), transparent 20%) 60%,
    var(--scalar-background-1) 100%
  );
  min-width: 3px;
  left: -1px;
  animation-direction: normal;
}
.fade-right {
  background: linear-gradient(
    90deg,
    color-mix(in srgb, var(--scalar-background-1), transparent 100%) 0%,
    color-mix(in srgb, var(--scalar-background-1), transparent 20%) 60%,
    var(--scalar-background-1) 100%
  );
  margin-left: -20px;
  min-width: 24px;
  right: -1px;
  top: 0;
}
@keyframes fadein {
  0% {
    opacity: 0;
  }
  15% {
    opacity: 1;
  }
}
</style>
