# This file is auto-generated by the Scalar Python config generator.
# Command: pnpm script generate-python-config
#
# Do not edit this file manually. Changes will be lost when the file is regenerated.
# Source of truth: packages/types/src/api-reference/

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from .enums import DocumentDownloadType, Layout, SearchHotKey, Theme
from .models import AgentConfig, OpenAPISource


class ScalarConfig(BaseModel):
    """Configuration for Scalar API Reference"""

    model_config = ConfigDict(
        extra="forbid",
        use_enum_values=False,
    )

    openapi_url: Optional[str] = Field(
        default=None,
        description="The OpenAPI URL that Scalar should load and use. If content or sources are provided, this parameter is ignored.",
    )

    title: Optional[str] = Field(
        default=None,
        description="The HTML <title> content, normally shown in the browser tab. Defaults to 'Scalar' if not provided.",
    )

    content: Optional[Union[str, Dict[str, Any]]] = Field(
        default=None,
        description="Directly pass an OpenAPI/Swagger document as a string (JSON or YAML) or as a dictionary. If sources are provided, this parameter is ignored.",
    )

    sources: Optional[List[OpenAPISource]] = Field(
        default=None,
        description="Add multiple OpenAPI documents to render all of them. Each source can have a title, slug, url, content, and default flag.",
    )

    scalar_js_url: str = Field(
        default="https://cdn.jsdelivr.net/npm/@scalar/api-reference",
        description="The URL to use to load the Scalar JavaScript. It is normally set to a CDN URL.",
    )

    scalar_proxy_url: str = Field(
        default="",
        description="The URL to use to set the Scalar Proxy.",
    )

    scalar_favicon_url: str = Field(
        default="",
        description="The URL of the favicon to use. It is normally shown in the browser tab.",
    )

    agent: Optional[AgentConfig] = Field(
        default=None,
        description="Agent Scalar config: set to AgentConfig(disabled=True) to disable Agent entirely.",
    )

    overrides: Dict[str, Any] = Field(
        default_factory=dict,
        description="A dictionary of additional configuration overrides to pass to Scalar. Default is {} which means no overrides are provided.",
    )

    authentication: Dict[str, Any] = Field(
        default_factory=dict,
        description="A dictionary of additional authentication information. Default is {} which means no authentication information is provided.",
    )

    base_server_url: str = Field(
        default="",
        description="If you want to prefix all relative servers with a base URL, you can do so here. Default is empty string.",
    )

    hide_client_button: bool = Field(
        default=False,
        description="Whether to show the client button from the reference sidebar and modal. Default is False which means the client button is shown.",
    )

    search_hot_key: SearchHotKey = Field(
        default=SearchHotKey.K,
        description="The hotkey to use for search. Default is 'k' (e.g. CMD+k).",
    )

    servers: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of OpenAPI Server Objects. Each item must have a required 'url' (string) and may have optional 'description' (string) and 'variables' (map).",
    )

    show_sidebar: bool = Field(
        default=True,
        description="A boolean to show the sidebar. Default is True which means the sidebar is shown.",
    )

    show_developer_tools: Literal["always", "localhost", "never"] = Field(
        default="localhost",
        description="Control the visibility of developer tools. Options are 'always', 'localhost', or 'never'. Default is 'localhost'.",
    )

    theme: Theme = Field(
        default=Theme.DEFAULT,
        description="The theme to use for Scalar. Default is 'default'.",
    )

    integration: Optional[str] = Field(
        default=None,
        description="The integration type. Default is None.",
    )

    persist_auth: bool = Field(
        default=False,
        description="Whether to persist authentication credentials in local storage. Default is False which means authentication is not persisted.",
    )

    telemetry: bool = Field(
        default=True,
        description="Whether to enable telemetry. Only tracks whether a request was sent through the API client. Default is True.",
    )

    layout: Layout = Field(
        default=Layout.MODERN,
        description="The layout to use for Scalar. Default is 'modern'.",
    )

    hide_models: bool = Field(
        default=False,
        description="A boolean to hide all models. Default is False which means all models are shown.",
    )

    document_download_type: DocumentDownloadType = Field(
        default=DocumentDownloadType.BOTH,
        description="Sets the file type of the document to download, set to 'none' to hide the download button. Default is 'both'.",
    )

    hide_download_button: bool = Field(
        default=False,
        description="A boolean to hide the download button. @deprecated Use document_download_type instead.",
    )

    hide_test_request_button: bool = Field(
        default=False,
        description="Whether to show the 'Test Request' button. Default is False which means the test request button is shown.",
    )

    hide_search: bool = Field(
        default=False,
        description="Whether to show the sidebar search bar. Default is False which means the search bar is shown.",
    )

    dark_mode: Optional[bool] = Field(
        default=None,
        description="Whether dark mode is on or off initially (light mode). Default is None which means the dark mode is not set.",
    )

    force_dark_mode_state: Optional[str] = Field(
        default=None,
        description="Force dark mode state to always be this state no matter what. Can be 'dark' or 'light'. Default is None.",
    )

    hide_dark_mode_toggle: bool = Field(
        default=False,
        description="Whether to show the dark mode toggle. Default is False which means the dark mode toggle is shown.",
    )

    hidden_clients: Union[bool, Dict[str, Union[bool, List[str]]], List[str]] = Field(
        default_factory=list,
        description="A dictionary with the keys being the target names and the values being a boolean to hide all clients of the target or a list clients. Default is [] which means no clients are hidden.",
    )

    custom_css: str = Field(
        default="",
        description="Custom CSS string to apply to the API reference. Default is empty string.",
    )

    with_default_fonts: bool = Field(
        default=True,
        description="Whether to use default fonts (Inter and JetBrains Mono). Default is True which means default fonts are used.",
    )

    default_open_all_tags: bool = Field(
        default=False,
        description="A boolean to open all tags by default. Default is False which means all tags are closed by default.",
    )

    expand_all_model_sections: bool = Field(
        default=False,
        description="Whether to expand all model sections by default. Default is False which means model sections are closed by default.",
    )

    expand_all_responses: bool = Field(
        default=False,
        description="Whether to expand all response sections by default. Default is False which means response sections are closed by default.",
    )

    order_required_properties_first: bool = Field(
        default=True,
        description="Whether to order required properties first in schema objects. Default is True which means required properties are shown first.",
    )
