# This file is auto-generated by the Scalar Python config generator.
# Command: pnpm script generate-python-config
#
# Do not edit this file manually. Changes will be lost when the file is regenerated.
# Source of truth: packages/types/src/api-reference/

from enum import Enum


class Theme(Enum):
    ALTERNATE = "alternate"
    DEFAULT = "default"
    MOON = "moon"
    PURPLE = "purple"
    SOLARIZED = "solarized"
    BLUE_PLANET = "bluePlanet"
    DEEP_SPACE = "deepSpace"
    SATURN = "saturn"
    KEPLER = "kepler"
    ELYSIAJS = "elysiajs"
    FASTIFY = "fastify"
    MARS = "mars"
    LASERWAVE = "laserwave"
    NONE = "none"


class Layout(Enum):
    MODERN = "modern"
    CLASSIC = "classic"


class SearchHotKey(Enum):
    A = "a"
    B = "b"
    C = "c"
    D = "d"
    E = "e"
    F = "f"
    G = "g"
    H = "h"
    I = "i"
    J = "j"
    K = "k"
    L = "l"
    M = "m"
    N = "n"
    O = "o"
    P = "p"
    Q = "q"
    R = "r"
    S = "s"
    T = "t"
    U = "u"
    V = "v"
    W = "w"
    X = "x"
    Y = "y"
    Z = "z"


class DocumentDownloadType(Enum):
    YAML = "yaml"
    JSON = "json"
    BOTH = "both"
    DIRECT = "direct"
    NONE = "none"
