# This file is auto-generated by the Scalar Python config generator.
# Command: pnpm script generate-python-config
#
# Do not edit this file manually. Changes will be lost when the file is regenerated.
# Source of truth: packages/types/src/api-reference/

from typing import Any, Dict, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

from .enums import Layout, SearchHotKey, Theme


class AgentConfig(BaseModel):
    """
    Agent Scalar configuration: AI chat in the API reference.
    Use key for production; use disabled=True to turn off Agent entirely.
    See: https://scalar.com/products/api-references/configuration#agent-scalar
    """

    model_config = ConfigDict(extra="forbid")

    key: Optional[str] = Field(
        default=None,
        description="Agent Scalar key for production. Required for Agent beyond localhost.",
    )

    disabled: Optional[bool] = Field(
        default=None,
        description="Set to True to disable Agent Scalar entirely.",
    )


class OpenAPISource(BaseModel):
    """
    Configuration for a single OpenAPI source
    """

    model_config = ConfigDict(extra="forbid")

    title: Optional[str] = Field(
        default=None,
        description="Display name for the API. If not provided, will fallback to 'API #1', 'API #2', etc.",
    )

    slug: Optional[str] = Field(
        default=None,
        description="URL identifier for the API. If not provided, will be auto-generated from the title or index.",
    )

    default: bool = Field(
        default=False,
        description="Whether this source should be the default when multiple sources are provided.",
    )

    url: Optional[str] = Field(
        default=None,
        description="URL to the OpenAPI document (JSON or YAML). Mutually exclusive with content.",
    )

    content: Optional[Union[str, Dict[str, Any]]] = Field(
        default=None,
        description="Direct OpenAPI content as string (JSON/YAML) or dictionary. Mutually exclusive with url.",
    )

    agent: Optional[AgentConfig] = Field(
        default=None,
        description="Optional Agent Scalar config for this source (key, disabled). See configuration docs.",
    )
