/**
 * This file is autogenerated. Do not edit it.
 *
 * Generated at: 2026-05-20T20:41:54.922Z
 */

/** An open tab in the workspace */
export type Tab = {
  /** Tab path or document identifier */
  path: string
  /** Tab title shown in the UI */
  title: string
  /** Tab icon (`request` or `document`) */
  icon?: string
}

/**
 * The currently selected proxy identifier for the workspace.
 *
 * @example
 * ```json
 * { "x-scalar-active-proxy": "my-proxy-id" }
 * ```
 */
export type XScalarActiveProxy = {
  /** The currently selected proxy identifier, or null when none is selected */
  'x-scalar-active-proxy'?: string | null
}

/**
 * Workspace tab configuration. Persists open tabs and the active tab across sessions.
 *
 * @example
 * ```yaml
 * x-scalar-tabs:
 * - path: /users
 * title: Users
 * x-scalar-active-tab: 0
 * ```
 */
export type XScalarTabs = {
  /** Tabs that are open in the workspace */
  'x-scalar-tabs'?: Tab[]
  /** Index of the currently active or focused tab */
  'x-scalar-active-tab'?: number
}
