/**
 * This file is autogenerated. Do not edit it.
 *
 * Generated at: 2026-05-21T18:54:27.562Z
 */

/**
 * The name of the currently selected AsyncAPI server for this API description.
 *
 * @example
 * ```yaml
 * x-scalar-selected-asyncapi-server: production
 * ```
 */
export type XScalarSelectedAsyncapiServer = {
  /** The name of the currently selected AsyncAPI server (key in document.servers) */
  'x-scalar-selected-asyncapi-server'?: string
}

/**
 * The URL of the currently selected server for this API description.
 *
 * @example
 * ```yaml
 * x-scalar-selected-server: https://api.example.com
 * ```
 */
export type XScalarSelectedServer = {
  /** The URL of the currently selected server */
  'x-scalar-selected-server'?: string
}
