/**
 * This file is autogenerated. Do not edit it.
 *
 * Generated at: 2026-05-20T20:41:54.922Z
 */

/** 
 * The URL of the currently selected server for this API description.
 * 
 * @example
 * ```yaml
 * x-scalar-selected-server: https://api.example.com
 * ```
 */
export type XScalarSelectedServer = {
  /** The URL of the currently selected server */
  "x-scalar-selected-server"?: string;
}
