/**
 * This file is autogenerated. Do not edit it.
 *
 * Generated at: 2026-05-21T19:11:01.297Z
 */

/**
 * The currently selected server for this API description. For OpenAPI documents the value is the server URL; for AsyncAPI documents the value is the server name (key in `document.servers`).
 *
 * @example
 * ```yaml
 * x-scalar-selected-server: https://api.example.com
 * ```
 */
export type XScalarSelectedServer = {
  /** The currently selected server. For OpenAPI documents this is the server URL; for AsyncAPI documents this is the server name (key in `document.servers`). */
  'x-scalar-selected-server'?: string
}
