name: 'Build'
description: 'Build using blacksmith runners and cache'
inputs:
  node-version:
    description: 'Node Version'
    required: false
    default: '20'
  packages:
    description: 'Package glob to build. Example: "@scalar/api-reference" or "packages/*"'
    required: true
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Check turbo cache dir
      shell: bash
      run: echo $TURBO_CACHE_DIR
    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
    - name: Use Blacksmith Node.js ${{ inputs.node-version }}
      uses: useblacksmith/setup-node@65c6ca86fdeb0ab3d85e78f57e4f6a7e4780b391
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - name: Persist turbo cache
      uses: useblacksmith/stickydisk@1a5dbf4b4af58d15a0bcadf7a3928a287d5a600f
      with:
        key: ${{ github.repository }}-${{ inputs.node-version }}-turbo-cache
        path: ${{ env.TURBO_CACHE_DIR }}
    - name: Check turbo cache dir
      shell: bash
      run: echo Connecting $TURBO_CACHE_DIR on ${{ github.repository }}-${{ inputs.node-version }}-turbo-cache
    - name: Install dependencies
      shell: bash
      run: pnpm install
    - name: Build specified packages
      shell: bash
      run: pnpm turbo --concurrency=100% --filter '${{inputs.packages}}' build
      env:
        NODE_OPTIONS: '--max_old_space_size=8192'
