import { apiReferencePluginSchema } from "@/api-reference/api-reference-plugin";
import { any, array, boolean, fn, literal, object, optional, string, union } from "@scalar/validation";

// TODO: support for default values
const externalUrlsSchema = object({
  dashboardUrl: string(),
  registryUrl: string(),
  proxyUrl: string(),
  apiBaseUrl: string(),
}) 

export const baseConfigurationSchema = object({
  title: optional(string()),
  slug: optional(string()),
  authentication: optional(any()),
  baseServerURL: optional(string()),
  hideClientButton: optional(boolean()),
  proxyUrl: optional(string()),
  oauth2RedirectUri: optional(string()),
  searchHotKey: optional(union([
    literal('a'),
    literal('b'),
    literal('c'),
    literal('d'),
    literal('e'),
    literal('f'),
    literal('g'),
    literal('h'),
    literal('i'),
    literal('j'),
    literal('k'),
    literal('l'),
    literal('m'),
    literal('n'),
    literal('o'),
    literal('p'),
    literal('q'),
    literal('r'),
    literal('s'),
    literal('t'),
    literal('u'),
    literal('v'),
    literal('w'),
    literal('x'),
    literal('y'),
    literal('z'),
  ])),
  servers: optional(array(string())),
  showSidebar: optional(boolean()),
  showDeveloperTools: optional(union([
    literal('localhost'),
    literal('always'),
    literal('never'),
  ])),
  showToolbar: optional(union([
    literal('localhost'),
    literal('always'),
    literal('never'),
  ])),
  operationTitleSource: optional(union([
    literal('summary'),
    literal('path'),
  ])),
  theme: optional(union([
    literal('default'),
    literal('alternate'),
    literal('moon'),
    literal('purple'),
    literal('solarized'),
    literal('bluePlanet'),
    literal('deepSpace'),
    literal('saturn'),
    literal('kepler'),
    literal('elysiajs'),
    literal('fastify'),
    literal('mars'),
    literal('laserwave'),
    literal('none'),
  ])),
  _integration: optional(union([
    literal('adonisjs'),
    literal('astro'),
    literal('docusaurus'),
    literal('dotnet'),
    literal('elysiajs'),
    literal('express'),
    literal('fastapi'),
    literal('fastify'),
    literal('go'),
    literal('hono'),
    literal('html'),
    literal('laravel'),
    literal('litestar'),
    literal('nestjs'),
    literal('nextjs'),
    literal('nitro'),
    literal('nuxt'),
    literal('platformatic'),
    literal('react'),
    literal('rust'),
    literal('svelte'),
    literal('vue'),
  ])),
  onRequestSent: optional(fn<(input: string) => void>()),
  persistAuth: optional(boolean()),
  plugins: optional(array(apiReferencePluginSchema)),
  telemetry: optional(boolean()),
  externalUrls: optional(externalUrlsSchema),
})