import { intersection, literal, object, optional, record, string, union } from '@scalar/validation'

import {
  XDefaultScopes,
  XScalarAuthUrl,
  XScalarCredentialsLocation,
  XScalarSecurityBody,
  XScalarSecurityQuery,
  XScalarTokenUrl,
  XTokenName,
  XusePkce,
} from '@/extensions/security'

const securitySchemeBase = object({
  description: optional(
    string({
      typeComment: 'A description for security scheme. CommonMark syntax MAY be used for rich text representation.',
    }),
  ),
})

export const apiKeySecurityScheme = object(
  {
    ...securitySchemeBase.properties,
    type: literal('apiKey'),
    name: string({ typeComment: 'REQUIRED. The name of the header, query or cookie parameter to be used.' }),
    in: union([literal('query'), literal('header'), literal('cookie')], {
      typeComment: 'REQUIRED. The location of the API key. Valid values are "query", "header", or "cookie".',
    }),
  },
  { typeName: 'ApiKeySecuritySchemeObject' },
)

export const httpSecurityScheme = object(
  {
    ...securitySchemeBase.properties,
    type: literal('http'),
    scheme: union([literal('basic'), literal('bearer')], {
      typeName: 'HttpSecuritySchemeScheme',
      typeComment:
        'REQUIRED. The name of the HTTP Authentication scheme to be used in the Authorization header as defined in RFC7235.',
    }),
    bearerFormat: optional(
      string({
        typeComment:
          'A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.',
      }),
    ),
  },
  { typeName: 'HttpSecuritySchemeObject' },
)

const oauthFlowExtensionObjects = [
  XScalarSecurityQuery,
  XScalarSecurityBody,
  XTokenName,
  XScalarAuthUrl,
  XScalarTokenUrl,
] as const

const oauthFlowCore = object(
  {
    refreshUrl: string({
      typeComment:
        'The URL to be used for obtaining refresh tokens. This MUST be in the form of a URL. The OAuth2 standard requires the use of TLS.',
    }),
    scopes: record(string(), string(), {
      typeComment:
        'REQUIRED. The available scopes for the OAuth2 security scheme. A map between the scope name and a short description for it. The map MAY be empty.',
      typeName: 'OAuthFlowScopes',
    }),
  },
  { typeName: 'OAuthFlowBaseCore' },
)

export const implicitOAuth2Flow = intersection(
  [
    oauthFlowCore,
    ...oauthFlowExtensionObjects,
    object({
      authorizationUrl: string({
        typeComment:
          'REQUIRED. The authorization URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard requires the use of TLS.',
      }),
    }),
  ],
  { typeName: 'ImplicitOAuthFlowObject' },
)

export const passwordOAuth2Flow = intersection(
  [
    oauthFlowCore,
    ...oauthFlowExtensionObjects,
    object({
      tokenUrl: string({
        typeComment:
          'REQUIRED. The token URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard requires the use of TLS.',
      }),
    }),
    XScalarCredentialsLocation,
  ],
  { typeName: 'PasswordOAuthFlowObject' },
)

export const clientCredentialsOAuth2Flow = intersection(
  [
    oauthFlowCore,
    ...oauthFlowExtensionObjects,
    object({
      tokenUrl: string({
        typeComment:
          'REQUIRED. The token URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard requires the use of TLS.',
      }),
    }),
    XScalarCredentialsLocation,
  ],
  { typeName: 'ClientCredentialsOAuthFlowObject' },
)

export const authorizationCodeOAuth2Flow = intersection(
  [
    oauthFlowCore,
    ...oauthFlowExtensionObjects,
    object({
      authorizationUrl: string({
        typeComment:
          'REQUIRED. The authorization URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard requires the use of TLS.',
      }),
      tokenUrl: string({
        typeComment:
          'REQUIRED. The token URL to be used for this flow. This MUST be in the form of a URL. The OAuth2 standard requires the use of TLS.',
      }),
    }),
    XusePkce,
    XScalarCredentialsLocation,
  ],
  { typeName: 'AuthorizationCodeOAuthFlowObject' },
)

export const oauth2Flows = object(
  {
    implicit: optional(implicitOAuth2Flow),
    password: optional(passwordOAuth2Flow),
    clientCredentials: optional(clientCredentialsOAuth2Flow),
    authorizationCode: optional(authorizationCodeOAuth2Flow),
  },
  { typeName: 'OAuthFlowsObject' },
)

export const oauth2SecurityScheme = intersection(
  [
    object({
      ...securitySchemeBase.properties,
      type: literal('oauth2'),
      flows: oauth2Flows,
    }),
    XDefaultScopes,
  ],
  { typeName: 'OAuth2SecuritySchemeObject' },
)

export const openIdConnectSecurityScheme = object(
  {
    ...securitySchemeBase.properties,
    type: literal('openIdConnect'),
    openIdConnectUrl: string({
      typeComment: 'REQUIRED. Well-known URL to discover the [[OpenID-Connect-Discovery]] provider metadata.',
    }),
  },
  { typeName: 'OpenIdConnectSecuritySchemeObject' },
)

export const securityScheme = union(
  [apiKeySecurityScheme, httpSecurityScheme, oauth2SecurityScheme, openIdConnectSecurityScheme],
  { typeName: 'SecuritySchemeObject' },
)
