name: Bug Report
description: If you’ve already asked for help with a problem and confirmed something is broken, create a bug report.
labels: ['bug']

body:
  - type: textarea
    id: actual-behaviour
    attributes:
      label: What happens?
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: 'How can we reproduce the issue?'
      placeholder: |
        1. Go to …
        2. Click on …
        3. Scroll down to …
        4. See error
    validations:
      required: true
  - type: input
    id: env-link
    attributes:
      label: Swagger/OpenAPI Example
      description: You can use https://sandbox.scalar.com to share an example with us.
      placeholder: https://sandbox.scalar.com/…
