name: 🐛 Bug report
description: If you’ve already asked for help with a problem and confirmed something is broken, create a bug report.
labels: ['bug']

body:
  - type: input
    id: actual-behaviour
    attributes:
      label: What happens?
    validations:
      required: true
  - type: input
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: env-link
    attributes:
      label: OpenAPI Document
      description: You can use https://sandbox.scalar.com or `npx @scalar/cli share openapi.json` to quickly upload an example.
      placeholder: https://sandbox.scalar.com/…
