name: 🐛 Bug Report
description: If you've already asked for help with a problem and confirmed something is broken, create a bug report.
title: "[Bug]: - <title>"
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: what did you expect to happen?
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behavior
      description: what did you actually happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Enter the software version
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge