<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Scalar.Aws.Lambda\Scalar.Aws.Lambda.csproj" />
  </ItemGroup>

</Project>
