/**
 * This file is autogenerated. Do not edit it.
 *
 * Generated at: 2026-07-27T12:26:32.709Z
 */

export type ArazzoInfoObject = {
  /** REQUIRED. A human readable title of the Arazzo Description. */
  title: string
  /** A short summary of the Arazzo Description. */
  summary?: string
  /** A description of the purpose of the workflows defined. CommonMark syntax MAY be used for rich text representation. */
  description?: string
  /** REQUIRED. The version identifier of the Arazzo document (distinct from the Arazzo Specification version). */
  version: string
}

export type ArazzoSourceDescriptionObject = {
  /** REQUIRED. A unique name for the source description. SHOULD conform to the regular expression [A-Za-z0-9_\-]+. */
  name: string
  /** REQUIRED. A URL to a source description to be used by a workflow. */
  url: string
  /** The type of source description. Possible values are "openapi", "asyncapi", or "arazzo". */
  type?: 'openapi' | 'asyncapi' | 'arazzo'
}

export type ArazzoExpressionTypeObject = {
  /** REQUIRED. The type of expression, for example "jsonpath" or "xpath". */
  type: string
  /** REQUIRED. The version of the expression type being used. */
  version: string
}

export type ArazzoSelectorObject = {
  /** REQUIRED. A Runtime Expression that defines the context to apply the selector to. */
  context: string
  /** REQUIRED. The selector expression to apply to the context. */
  selector: string
  /** REQUIRED. The type of selector expression, for example "jsonpath", "xpath", or "jsonpointer". MAY be an Expression Type Object to pin a specific expression language version. */
  type: string | ArazzoExpressionTypeObject
}

export type ArazzoParameterObject = {
  /** REQUIRED. The name of the parameter. */
  name: string
  /** The location of the parameter. REQUIRED unless the parameter is defined with a Reusable Object referencing a Components parameter. */
  in?: 'path' | 'query' | 'querystring' | 'header' | 'cookie' | 'channel'
  /** REQUIRED. The value to pass in the parameter. Can be a constant, a Runtime Expression, or a Selector Object. */
  value: unknown | string | ArazzoSelectorObject
}

export type ArazzoReusableObject = {
  /** REQUIRED. A Runtime Expression used to reference the desired object. */
  reference: string
  /** Sets a value of the referenced parameter. Only applicable for parameter object references. */
  value?: unknown
}

export type ArazzoPayloadReplacementObject = {
  /** REQUIRED. A JSON Pointer, XPath Expression, or JSONPath which MUST be resolved against the request body. */
  target: string
  /** The selector expression type to use, for example "jsonpath", "xpath", or "jsonpointer". */
  targetSelectorType?: string | ArazzoExpressionTypeObject
  /** REQUIRED. The value set within the target location. Can be a constant, a Runtime Expression, or a Selector Object. */
  value: unknown | string | ArazzoSelectorObject
}

export type ArazzoRequestBodyObject = {
  /** The Content-Type for the request content. If omitted, refer to the Content-Type on the targeted operation. */
  contentType?: string
  /** A value representing the request body payload. May be a literal value or contain Runtime Expressions or Selector Objects. */
  payload?: unknown
  /** A list of locations and values to set within a payload. */
  replacements?: ArazzoPayloadReplacementObject[]
}

export type ArazzoCriterionObject = {
  /** A Runtime Expression that defines the context of the condition. REQUIRED when type is regex, jsonpath, or xpath. */
  context?: string
  /** REQUIRED. The condition to evaluate, combining Runtime Expressions, literals, and operators. */
  condition: string
  /** The type of condition: "simple" (default), "regex", "jsonpath", or "xpath". MAY be an Expression Type Object to pin a specific expression language version. */
  type?: string | ArazzoExpressionTypeObject
}

export type ArazzoSuccessActionObject = {
  /** REQUIRED. The name of the success action. */
  name: string
  /** REQUIRED. The type of action to take. */
  type: 'end' | 'goto'
  /** The workflowId to transfer to upon success. Only relevant when type is "goto". */
  workflowId?: string
  /** The stepId to transfer to upon success. Only relevant when type is "goto". */
  stepId?: string
  /** A list of parameters to pass to the referenced workflow or step. */
  parameters?: (ArazzoParameterObject | ArazzoReusableObject)[]
  /** A list of assertions to determine if this action applies. */
  criteria?: ArazzoCriterionObject[]
}

export type ArazzoFailureActionObject = {
  /** REQUIRED. The name of the failure action. */
  name: string
  /** REQUIRED. The type of action to take. */
  type: 'end' | 'retry' | 'goto'
  /** The workflowId to transfer to. Only relevant when type is "goto" or "retry". */
  workflowId?: string
  /** The stepId to transfer to. Only relevant when type is "goto" or "retry". */
  stepId?: string
  /** A list of parameters to pass to the referenced workflow or step. */
  parameters?: (ArazzoParameterObject | ArazzoReusableObject)[]
  /** A non-negative decimal indicating the seconds to delay before the retry. */
  retryAfter?: number
  /** A non-negative integer indicating how many times to retry. */
  retryLimit?: number
  /** A list of assertions to determine if this action applies. */
  criteria?: ArazzoCriterionObject[]
}

export type ArazzoStepObject = {
  /** A description of the step. */
  description?: string
  /** REQUIRED. Unique string to represent the step. */
  stepId: string
  /** The name of an existing, resolvable operation within one of the sourceDescriptions. Mutually exclusive with operationPath, channelPath, and workflowId. */
  operationId?: string
  /** A Source Description Object combined with a JSON Pointer to reference an operation. Mutually exclusive with operationId, channelPath, and workflowId. */
  operationPath?: string
  /** A Source Description Object combined with a JSON Pointer to reference an AsyncAPI channel. Mutually exclusive with operationId, operationPath, and workflowId. */
  channelPath?: string
  /** The workflowId of an existing workflow to invoke. Mutually exclusive with operationId, operationPath, and channelPath. */
  workflowId?: string
  /** Whether this step sends or receives a message. Only relevant when channelPath is set. */
  action?: 'send' | 'receive'
  /** A Runtime Expression identifying the correlation ID used to pair send/receive steps. */
  correlationId?: string
  /** A list of parameters to pass to the referenced operation, channel, or workflow. */
  parameters?: (ArazzoParameterObject | ArazzoReusableObject)[]
  requestBody?: ArazzoRequestBodyObject
  /** A list of assertions to determine step success. */
  successCriteria?: ArazzoCriterionObject[]
  /** An array of success action objects to run upon step success. */
  onSuccess?: (ArazzoSuccessActionObject | ArazzoReusableObject)[]
  /** An array of failure action objects to run upon step failure. */
  onFailure?: (ArazzoFailureActionObject | ArazzoReusableObject)[]
  /** Map of output name to a Runtime Expression or Selector Object. */
  outputs?: Record<string, string | ArazzoSelectorObject>
  /** A non-negative integer indicating the timeout in seconds for this step. */
  timeout?: number
  /** A list of stepIds that MUST be completed before this step can be processed. */
  dependsOn?: string[]
}

export type ArazzoWorkflowObject = {
  /** REQUIRED. Unique string to represent the workflow. */
  workflowId: string
  /** A summary of the purpose or objective of the workflow. */
  summary?: string
  /** A description of the workflow. */
  description?: string
  /** A JSON Schema 2020-12 object representing the input parameters used by this workflow. */
  inputs?: unknown
  /** A list of workflowIds that MUST be completed before this workflow can be processed. */
  dependsOn?: string[]
  /** REQUIRED. An ordered list of steps this workflow executes. */
  steps: ArazzoStepObject[]
  /** An array of success action objects that apply to all steps in this workflow. */
  successActions?: (ArazzoSuccessActionObject | ArazzoReusableObject)[]
  /** An array of failure action objects that apply to all steps in this workflow. */
  failureActions?: (ArazzoFailureActionObject | ArazzoReusableObject)[]
  /** Map of output name to a Runtime Expression or Selector Object. */
  outputs?: Record<string, string | ArazzoSelectorObject>
  /** A list of parameters applicable for all steps in this workflow. */
  parameters?: (ArazzoParameterObject | ArazzoReusableObject)[]
}

export type ArazzoComponentsObject = {
  /** An object to hold reusable JSON Schema objects to be referenced from workflow inputs. */
  inputs?: Record<string, unknown>
  /** An object to hold reusable Parameter Objects. */
  parameters?: Record<string, ArazzoParameterObject>
  /** An object to hold reusable Success Action Objects. */
  successActions?: Record<string, ArazzoSuccessActionObject>
  /** An object to hold reusable Failure Action Objects. */
  failureActions?: Record<string, ArazzoFailureActionObject>
}

/** Root Arazzo 1.1.0 document. */
export type ArazzoDocumentCore = {
  /** REQUIRED. The version number of the Arazzo Specification that this Arazzo Description uses. */
  arazzo: string
  /** A URI-reference for the Arazzo Description, also serving as its base URI for resolving relative references. */
  $self?: string
  info: ArazzoInfoObject
  /** REQUIRED. A list of source descriptions this Arazzo Description applies to. */
  sourceDescriptions: ArazzoSourceDescriptionObject[]
  /** REQUIRED. A list of workflows describing the call sequences. */
  workflows: ArazzoWorkflowObject[]
  components?: ArazzoComponentsObject
}

/** Client-side navigation tree persisted on the document. Matches `TraversedDocumentObjectRef` in strict OpenAPI schemas. */
export type XScalarNavigation = {
  /** Serialized client navigation tree (`TraversedDocument`) for this API description */
  'x-scalar-navigation'?: any
}

/**
 * Original document source URL when the API description was loaded from an external source.
 *
 * @example
 * ```yaml
 * x-scalar-original-source-url: https://example.com/openapi.yaml
 * ```
 */
export type XScalarOriginalSourceUrl = {
  /** Original document source URL when loaded from an external source */
  'x-scalar-original-source-url'?: string
}

/**
 * Tracks the original document hash when loading from an external source. Used to detect modifications since last save.
 *
 * @example
 * ```yaml
 * x-scalar-original-document-hash: "abc123"
 * ```
 */
export type XScalarOriginalDocumentHash = {
  /** Hash of the document as originally loaded from an external source */
  'x-scalar-original-document-hash': string
}

/**
 * Tracks whether the document has been modified since it was last saved.
 *
 * @example
 * ```yaml
 * x-scalar-is-dirty: true
 * ```
 */
export type XScalarIsDirty = {
  /** When true, the document has unsaved changes */
  'x-scalar-is-dirty'?: boolean
}

/**
 * Whether the document is in watch mode (reloads when the source file changes).
 *
 * @example
 * ```yaml
 * x-scalar-watch-mode: true
 * ```
 */
export type XScalarWatchMode = {
  /** When true, the document is watched for external file changes */
  'x-scalar-watch-mode'?: boolean
}

/** Registry meta namespace and slug */
export type XScalarRegistryMetaInner = {
  /** The namespace under which this registry meta is scoped. */
  namespace: string
  /** A unique slug identifier for this registry meta within the namespace. */
  slug: string
  /** The version of the registry meta. */
  version: string
  /** Last known commit hash of this document. Is going to be used to track if the document has been modified since it was last saved. */
  commitHash?: string
  /** Registry commit hash that the cached `hasConflict` flag was computed against. When the registry advertises a different hash later, the cached result is stale and the conflict check must be re-run. */
  conflictCheckedAgainstHash?: string
  /** Cached outcome of the last conflict check, valid only while `conflictCheckedAgainstHash` matches the registry current hash for this version. */
  hasConflict?: boolean
}

/**
 * Registry sync metadata for a document published to Scalar Registry.
 *
 * @example
 * ```yaml
 * x-scalar-registry-meta:
 * namespace: acme
 * slug: public-api
 * version: "1.0.0"
 * ```
 */
export type XScalarRegistryMeta = {
  /** Registry meta namespace and slug */
  'x-scalar-registry-meta'?: XScalarRegistryMetaInner
}

/** Arazzo document-level Scalar extensions shared with workspace tooling. */
export type ArazzoExtensions = XScalarNavigation &
  XScalarOriginalSourceUrl &
  XScalarOriginalDocumentHash &
  XScalarIsDirty &
  XScalarWatchMode &
  XScalarRegistryMeta

/** Root Arazzo 1.1.0 document including Scalar workspace extensions (ArazzoExtensions). */
export type ArazzoDocument = ArazzoDocumentCore & ArazzoExtensions
