import type { TraversedEntry } from '@scalar/workspace-store/schemas/navigation'

export const galaxySidebar = [
  {
    'id': 'scalar-galaxy/description/introduction',
    'title': 'Introduction',
    'type': 'text',
  },
  {
    'id': 'scalar-galaxy/description/resources',
    'title': 'Resources',
    'type': 'text',
    'children': [],
  },
  {
    'id': 'scalar-galaxy/description/markdown-support',
    'title': 'Markdown Support',
    'type': 'text',
    'children': [],
  },
  {
    'id': 'scalar-galaxy/tag/authentication',
    'title': 'Authentication',
    'name': 'Authentication',
    'description':
      'Some endpoints are public, but some require authentication. We provide all the required endpoints to create an account and authorize yourself.',
    'children': [
      {
        'id': 'scalar-galaxy/tag/authentication/POST/user/signup',
        'title': 'Create a user',
        'path': '/user/signup',
        'method': 'post',
        'ref': '#/paths/~1user~1signup/post',
        'type': 'operation',
        'isDeprecated': true,
        'children': [
          {
            'type': 'example',
            'id': 'scalar-galaxy/tag/authentication/POST/user/signup/example/marc',
            'title': 'Marc',
            'name': 'Marc',
          },
          {
            'type': 'example',
            'id': 'scalar-galaxy/tag/authentication/POST/user/signup/example/cam',
            'title': 'Cam',
            'name': 'Cam',
          },
          {
            'type': 'example',
            'id': 'scalar-galaxy/tag/authentication/POST/user/signup/example/hans',
            'title': 'Hans',
            'name': 'Hans',
          },
        ],
      },
      {
        'id': 'scalar-galaxy/tag/authentication/POST/auth/token',
        'title': 'Get a token',
        'path': '/auth/token',
        'method': 'post',
        'ref': '#/paths/~1auth~1token/post',
        'type': 'operation',
        'isDeprecated': false,
      },
      {
        'id': 'scalar-galaxy/tag/authentication/GET/me',
        'title': 'Get authenticated user',
        'path': '/me',
        'method': 'get',
        'ref': '#/paths/~1me/get',
        'type': 'operation',
        'isDeprecated': false,
      },
    ],
    'isGroup': false,
    'isWebhooks': false,
    'type': 'tag',
    'xKeys': {
      'x-scalar-order': [
        'scalar-galaxy/tag/authentication/POST/user/signup',
        'scalar-galaxy/tag/authentication/POST/auth/token',
        'scalar-galaxy/tag/authentication/GET/me',
      ],
    },
  },
  {
    'id': 'scalar-galaxy/tag/planets',
    'title': 'Planets',
    'name': 'Planets',
    'description': 'Everything about planets',
    'children': [
      {
        'id': 'scalar-galaxy/tag/planets/GET/planets',
        'title': 'Get all planets',
        'path': '/planets',
        'method': 'get',
        'ref': '#/paths/~1planets/get',
        'type': 'operation',
        'isDeprecated': false,
      },
      {
        'id': 'scalar-galaxy/tag/planets/POST/planets',
        'title': 'Create a planet',
        'path': '/planets',
        'method': 'post',
        'ref': '#/paths/~1planets/post',
        'type': 'operation',
        'isDeprecated': false,
      },
      {
        'id': 'scalar-galaxy/tag/planets/GET/planets/{planetId}',
        'title': 'Get a planet',
        'path': '/planets/{planetId}',
        'method': 'get',
        'ref': '#/paths/~1planets~1{planetId}/get',
        'type': 'operation',
        'isDeprecated': false,
      },
      {
        'id': 'scalar-galaxy/tag/planets/PUT/planets/{planetId}',
        'title': 'Update a planet',
        'path': '/planets/{planetId}',
        'method': 'put',
        'ref': '#/paths/~1planets~1{planetId}/put',
        'type': 'operation',
        'isDeprecated': true,
      },
      {
        'id': 'scalar-galaxy/tag/planets/DELETE/planets/{planetId}',
        'title': 'Delete a planet',
        'path': '/planets/{planetId}',
        'method': 'delete',
        'ref': '#/paths/~1planets~1{planetId}/delete',
        'type': 'operation',
        'isDeprecated': false,
      },
      {
        'id': 'scalar-galaxy/tag/planets/POST/planets/{planetId}/image',
        'title': 'Upload an image to a planet',
        'path': '/planets/{planetId}/image',
        'method': 'post',
        'ref': '#/paths/~1planets~1{planetId}~1image/post',
        'type': 'operation',
        'isDeprecated': false,
      },
      {
        'id': 'scalar-galaxy/tag/planets/webhook/POST/newplanet',
        'title': 'newPlanet',
        'name': 'newPlanet',
        'ref': '#/webhooks/newPlanet/post',
        'method': 'post',
        'type': 'webhook',
        'isDeprecated': false,
      },
    ],
    'isGroup': false,
    'isWebhooks': false,
    'type': 'tag',
    'xKeys': {
      'x-scalar-order': [
        'scalar-galaxy/tag/planets/GET/planets',
        'scalar-galaxy/tag/planets/POST/planets',
        'scalar-galaxy/tag/planets/GET/planets/{planetId}',
        'scalar-galaxy/tag/planets/PUT/planets/{planetId}',
        'scalar-galaxy/tag/planets/DELETE/planets/{planetId}',
        'scalar-galaxy/tag/planets/POST/planets/{planetId}/image',
        'scalar-galaxy/tag/planets/webhook/POST/newplanet',
      ],
    },
  },
  {
    'id': 'scalar-galaxy/tag/celestial-bodies',
    'title': 'Celestial Bodies',
    'name': 'Celestial Bodies',
    'description': 'Celestial bodies are the planets and satellites in the Scalar Galaxy.',
    'children': [
      {
        'id': 'scalar-galaxy/tag/celestial-bodies/POST/celestial-bodies',
        'title': 'Create a celestial body',
        'path': '/celestial-bodies',
        'method': 'post',
        'ref': '#/paths/~1celestial-bodies/post',
        'type': 'operation',
        'isDeprecated': false,
      },
    ],
    'isGroup': false,
    'isWebhooks': false,
    'type': 'tag',
    'xKeys': {
      'x-scalar-order': ['scalar-galaxy/tag/celestial-bodies/POST/celestial-bodies'],
    },
  },
  {
    'type': 'models',
    'id': 'scalar-galaxy/models',
    'title': 'Models',
    'name': 'Models',
    'children': [
      {
        'id': 'scalar-galaxy/model/user',
        'title': 'User',
        'name': 'User',
        'ref': '#/components/schemas/User',
        'type': 'model',
      },
      {
        'id': 'scalar-galaxy/model/credentials',
        'title': 'Credentials',
        'name': 'Credentials',
        'ref': '#/components/schemas/Credentials',
        'type': 'model',
      },
      {
        'id': 'scalar-galaxy/model/token',
        'title': 'Token',
        'name': 'Token',
        'ref': '#/components/schemas/Token',
        'type': 'model',
      },
      {
        'id': 'scalar-galaxy/model/celestialbody',
        'title': 'CelestialBody',
        'name': 'CelestialBody',
        'ref': '#/components/schemas/CelestialBody',
        'type': 'model',
      },
      {
        'id': 'scalar-galaxy/model/planet',
        'title': 'Planet',
        'name': 'Planet',
        'ref': '#/components/schemas/Planet',
        'type': 'model',
      },
      {
        'id': 'scalar-galaxy/model/satellite',
        'title': 'Satellite',
        'name': 'Satellite',
        'ref': '#/components/schemas/Satellite',
        'type': 'model',
      },
      {
        'id': 'scalar-galaxy/model/paginatedresource',
        'title': 'PaginatedResource',
        'name': 'PaginatedResource',
        'ref': '#/components/schemas/PaginatedResource',
        'type': 'model',
      },
    ],
  },

  {
    id: 'tag/long-string-test',
    title: 'Long string that needs to wrap to multiple lines',
    name: 'Long String Tests',
    description: '',
    children: [
      {
        id: 'tag/long-string-test/post/1',
        title: 'Long string that needs to wrap to multiple lines',
        path: '/long/path/that/needs/to/be/handled/properly/in/the/sidebar',
        method: 'post',
        ref: '#/...',
        type: 'operation',
      },
      {
        id: 'tag/long-string-test/post/auth/token',
        title: '/long/uri/that/also/needs/to/be/handled/properly/in/the/sidebar',
        path: '/long/uri/that/also/needs/to/be/handled/properly/in/the/sidebar',
        method: 'post',
        ref: '#/...',
        type: 'operation',
      },
      {
        id: 'model/long-string-test/user',
        title: 'LongPascalCaseStringThatNeedsToWrapToMultipleLines',
        name: 'LongPascalCaseStringThatNeedsToWrapToMultipleLines',
        ref: '#/...',
        type: 'model',
      },
    ],
    isGroup: false,
    isWebhooks: false,
    type: 'tag',
    xKeys: {},
  },
] satisfies TraversedEntry[]
