services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - '8081:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./playground-realm.json:/opt/keycloak/data/import/playground-realm.json
    command: start-dev --import-realm
