export const ICONS = [
  'Add',
  'CheckMark',
  'ChevronDown',
  'ChevronLeft',
  'ChevronRight',
  'ChevronUp',
  'Close',
  'DarkMode',
  'Ellipses',
  'ExternalLink',
  'GitHub',
  'LightDarkModeToggle',
  'LightMode',
  'Logo',
  'LogoAPI',
  'LogoClient',
  'LogoMarket',
  'LogoSwagger',
  'Menu',
  'Search'
] as const