services:
  api-reference:
    image: scalarapi/api-reference:latest
    ports:
      - '8080:8080'
    volumes:
      # Mount the API documents directory
      - ./api-docs:/api-docs:ro
    environment:
      # Optional: Add global configuration like theme
      API_REFERENCE_CONFIG: |
        {
          "theme": "purple"
        }
    restart: unless-stopped
