services:
  api-reference:
    image: scalarapi/api-reference:latest
    ports:
      - '8080:8080'
    volumes:
      # Mount the API documents directory
      - ./api-docs:/mounted-docs:ro
    environment:
      # Optional: Add global configuration like theme
      API_REFERENCE_CONFIG: |
        {
          "theme": "purple"
        }
      # Optional: Custom mount directory and base URL
      # OPENAPI_MOUNT_DIR: /mounted-docs
      # OPENAPI_BASE_URL: /docs
    restart: unless-stopped
