/**
 * IPC wire-protocol types and renderer-side transport types for the custom
 * fetch bridge.  These are imported by the main process too, so keep them
 * environment-agnostic (no DOM-only types in `IpcFetchRequest` /
 * `IpcFetchResponse`).
 */

/** Serializable fetch request payload sent from renderer to main process via IPC. */
export type IpcFetchRequest = {
  url: string
  method?: string
  headers?: Record<string, string>
  body?: ArrayBuffer
  cache?: string
  credentials?: string
  integrity?: string
  keepalive?: boolean
  mode?: string
  redirect?: string
  referrer?: string
  referrerPolicy?: string
  /**
   * Opaque ID generated by the renderer when an `AbortSignal` is present.
   * The renderer calls `customFetchAbort(abortId)` when the signal fires,
   * and the main process uses it to look up and call the matching `AbortController`.
   */
  abortId?: string
}

/** Serializable fetch response payload returned from main process to renderer via IPC. */
export type IpcFetchResponse = {
  status: number
  statusText: string
  /** Ordered list of [name, value] pairs; preserves multiple Set-Cookie entries. */
  headers: [string, string][]
  /**
   * Buffered response body, or `null` when:
   * - The status is a null-body status (204, 205, 304) — Fetch spec forbids a body.
   * - `streamId` is set — body arrives via IPC stream events instead.
   */
  body: ArrayBuffer | null
  /** Final URL after any redirects; mirrors Response.url for the renderer. */
  url: string
  /** Whether one or more redirects occurred; mirrors Response.redirected. */
  redirected: boolean
  /**
   * Present when the response body is delivered via incremental IPC events rather
   * than as a single `body` ArrayBuffer.  Used for SSE / chunked-transfer responses.
   * The renderer subscribes via `window.api.customFetchStream({ streamId, callbacks })`.
   */
  streamId?: string
}

/**
 * Extended response type accepted by the renderer-side transport.
 *
 * `IpcFetchResponse.body` is `ArrayBuffer | null` (IPC-serialisable).  A
 * streaming transport (e.g. a test double or a future IPC streaming channel)
 * may also supply a `ReadableStream<Uint8Array>` so that callers can consume
 * SSE / chunked responses incrementally without buffering.
 */
export type TransportResponse = Omit<IpcFetchResponse, 'body'> & {
  body: ArrayBuffer | null | ReadableStream<Uint8Array>
}

/**
 * A transport performs the actual HTTP request and returns a response.
 *
 * In production this is backed by the Electron IPC bridge; in tests it can be
 * any mock implementation.
 */
export type Transport = (request: IpcFetchRequest) => Promise<TransportResponse>
