//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Scalar Java enum generator.
//     Source: /packages/snippetz/src/clients.ts
//     Command: pnpm generate:java-enums
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package com.scalar.maven.webjar.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Represents the different clients available in Scalar.
 */
public enum ScalarClient {
    /**
     * AsyncHttp client.
     */
    ASYNC_HTTP("asynchttp"),

    /**
     * Axios client.
     */
    AXIOS("axios"),

    /**
     * clj-http client.
     */
    CLJ_HTTP("clj_http"),

    /**
     * Cohttp client.
     */
    CO_HTTP("cohttp"),

    /**
     * Curl client.
     */
    CURL("curl"),

    /**
     * Fetch client.
     */
    FETCH("fetch"),

    /**
     * Guzzle client.
     */
    GUZZLE("guzzle"),

    /**
     * Http client.
     */
    HTTP("http"),

    /**
     * HTTP/1.1 client.
     */
    HTTP_11("http1.1"),

    /**
     * HttpClient client.
     */
    HTTP_CLIENT("httpclient"),

    /**
     * HTTPie client.
     */
    HTTPIE("httpie"),

    /**
     * HTTPX (Async) client.
     */
    HTTPX_ASYNC("httpx_async"),

    /**
     * HTTPX (Sync) client.
     */
    HTTPX_SYNC("httpx_sync"),

    /**
     * httr client.
     */
    HTTR("httr"),

    /**
     * jQuery client.
     */
    J_QUERY("jquery"),

    /**
     * Libcurl client.
     */
    LIBCURL("libcurl"),

    /**
     * net::http client.
     */
    NATIVE("native"),

    /**
     * java.net.http client.
     */
    NET_HTTP("nethttp"),

    /**
     * NSURLSession client.
     */
    NSURL_SESSION("nsurlsession"),

    /**
     * ofetch client.
     */
    O_FETCH("ofetch"),

    /**
     * OkHttp client.
     */
    OK_HTTP("okhttp"),

    /**
     * http.client client.
     */
    PYTHON3("python3"),

    /**
     * Requests client.
     */
    REQUESTS("requests"),

    /**
     * reqwest client.
     */
    REQWEST("reqwest"),

    /**
     * Invoke-RestMethod client.
     */
    REST_METHOD("restmethod"),

    /**
     * RestSharp client.
     */
    REST_SHARP("restsharp"),

    /**
     * undici client.
     */
    UNDICI("undici"),

    /**
     * Unirest client.
     */
    UNIREST("unirest"),

    /**
     * Invoke-WebRequest client.
     */
    WEB_REQUEST("webrequest"),

    /**
     * Wget client.
     */
    WGET("wget"),

    /**
     * XHR client.
     */
    XHR("xhr");

    private final String value;

    ScalarClient(String value) {
        this.value = value;
    }

    /**
     * Creates a ScalarClient from a string value.
     *
     * @param value the string value
     * @return the corresponding ScalarClient
     * @throws IllegalArgumentException if the value is not recognized
     */
    @JsonCreator
    public static ScalarClient fromValue(String value) {
        for (ScalarClient client : values()) {
            if (client.value.equals(value)) {
                return client;
            }
        }
        throw new IllegalArgumentException("Unknown client: " + value);
    }

    /**
     * Gets the string value for JSON serialization.
     *
     * @return the string value
     */
    @JsonValue
    public String getValue() {
        return value;
    }
}