// Checkout /tooling/scripts/README.md for more information on how to use this command.

import fs from 'node:fs/promises'
import path from 'node:path'

import as from 'ansis'
import { Command } from 'commander'
import { z } from 'zod'

import { getWorkspaceRoot } from '@/helpers'

const DEFAULT_OUTPUT = 'documentation/guides/cli'

/** Page that collects the top-level commands too small for a page of their own */
const GENERAL_PAGE = 'general'

/** Groups people reach for first lead the reference; groups not listed follow in CLI order */
const PAGE_ORDER = ['document', 'project', 'registry', 'auth', 'team', 'schema', 'sdk', 'access-group']

const GENERATED_NOTICE =
  '<!-- Generated by `pnpm script generate-cli-docs` from `scalar context`. Do not edit by hand. -->'

const contextArgumentSchema = z.object({
  name: z.string(),
  description: z.string(),
  required: z.boolean(),
  variadic: z.boolean(),
  default: z.unknown().optional(),
  choices: z.array(z.string()).optional(),
})

const contextOptionSchema = z.object({
  flags: z.string(),
  description: z.string(),
  mandatory: z.boolean(),
  default: z.unknown().optional(),
  choices: z.array(z.string()).optional(),
  env: z.string().optional(),
})

type ContextCommand = {
  name: string
  command: string
  usage: string
  description: string
  runnable: boolean
  arguments: z.infer<typeof contextArgumentSchema>[]
  options: z.infer<typeof contextOptionSchema>[]
  commands: ContextCommand[]
}

const contextCommandSchema: z.ZodType<ContextCommand> = z.lazy(() =>
  z.object({
    name: z.string(),
    command: z.string(),
    usage: z.string(),
    description: z.string(),
    runnable: z.boolean(),
    arguments: z.array(contextArgumentSchema),
    options: z.array(contextOptionSchema),
    commands: z.array(contextCommandSchema),
  }),
)

/** The subset of `scalar context` output the docs are rendered from */
export const cliContextSchema = z.object({
  version: z.string(),
  commands: z.array(contextCommandSchema),
})

export type CliContext = z.infer<typeof cliContextSchema>

/** One generated page of the command reference */
type CommandPage = {
  /** File name without extension, also the URL segment */
  slug: string
  title: string
  description: string
  commands: ContextCommand[]
}

const isHelpOption = (option: { flags: string }) => option.flags === '-h, --help'

const rank = (slug: string) => {
  const index = PAGE_ORDER.indexOf(slug)
  return index === -1 ? PAGE_ORDER.length : index
}

/** Every command in the tree that does something itself, depth first */
export const flattenRunnable = (commands: ContextCommand[]): ContextCommand[] =>
  commands.flatMap((command) => [...(command.runnable ? [command] : []), ...flattenRunnable(command.commands)])

/**
 * Splits the command tree into pages: one per command group, plus a general page for the
 * top-level commands that have at most one subcommand of their own.
 */
export const groupIntoPages = (context: CliContext): CommandPage[] => {
  const pages: CommandPage[] = []
  const general: ContextCommand[] = []

  for (const command of context.commands) {
    if (command.name === 'help') {
      continue
    }

    if (flattenRunnable(command.commands).length >= 2) {
      pages.push({
        slug: command.name,
        title: `scalar ${command.name}`,
        description: command.description,
        commands: flattenRunnable(command.commands),
      })
    } else {
      general.push(...flattenRunnable([command]))
    }
  }

  pages.sort((a, b) => rank(a.slug) - rank(b.slug))

  if (general.length) {
    pages.push({
      slug: GENERAL_PAGE,
      title: 'General',
      description: 'Commands for the CLI itself: help, upgrades, shell completion, and agent context',
      commands: general,
    })
  }

  return pages
}

/** Heading for a command within its page, relative to the page's own group */
export const commandHeading = (command: ContextCommand, page: CommandPage) => {
  const prefix = page.slug === GENERAL_PAGE ? 'scalar ' : `scalar ${page.slug} `
  return command.command.startsWith(prefix) ? command.command.slice(prefix.length) : command.command
}

/** GitHub-style heading anchor, matching how the docs site slugs headings */
export const anchor = (heading: string) =>
  heading
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')

const escapeCell = (value: string) => value.replace(/\|/g, '\\|').replace(/\n/g, ' ')

const code = (value: string) => `\`${escapeCell(value)}\``

/** Summary text, capitalized and without a trailing period, for lists and tables */
const phrase = (value: string) => {
  const trimmed = value.trim().replace(/\.$/, '')
  return trimmed.charAt(0).toUpperCase() + trimmed.slice(1)
}

const sentence = (value: string) => `${phrase(value)}.`

const formatDefault = (value: unknown) => {
  if (value === undefined) {
    return ''
  }
  return code(typeof value === 'string' ? value : JSON.stringify(value))
}

/** Description cell with choices, environment fallback, and requirement folded in */
const describe = ({
  description,
  choices,
  env,
  required,
}: {
  description: string
  choices?: string[]
  env?: string
  required?: boolean
}) => {
  const parts = [escapeCell(sentence(description))]
  if (required) {
    parts.unshift('**Required.**')
  }
  if (choices?.length) {
    parts.push(`One of ${choices.map(code).join(', ')}.`)
  }
  if (env) {
    parts.push(`Falls back to ${code(env)}.`)
  }
  return parts.join(' ')
}

/** Table of arguments or options, with a Default column only when something has a default */
const parameterTable = (label: string, rows: { name: string; description: string; default: unknown }[]) => {
  const withDefaults = rows.some((row) => row.default !== undefined)
  return table(
    withDefaults ? [label, 'Description', 'Default'] : [label, 'Description'],
    rows.map((row) =>
      withDefaults ? [code(row.name), row.description, formatDefault(row.default)] : [code(row.name), row.description],
    ),
  )
}

function table(header: string[], rows: string[][]) {
  return [
    `| ${header.join(' | ')} |`,
    `| ${header.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ]
}

export const renderCommand = (command: ContextCommand, page: CommandPage): string[] => {
  const lines = [
    `## ${commandHeading(command, page)}`,
    '',
    sentence(command.description),
    '',
    '```bash',
    command.usage,
    '```',
  ]

  if (command.arguments.length) {
    lines.push(
      '',
      '**Arguments**',
      '',
      ...parameterTable(
        'Argument',
        command.arguments.map((argument) => ({
          name: argument.variadic ? `${argument.name}...` : argument.name,
          description: describe(argument),
          default: argument.default,
        })),
      ),
    )
  }

  const options = command.options.filter((option) => !isHelpOption(option))
  if (options.length) {
    lines.push(
      '',
      '**Options**',
      '',
      ...parameterTable(
        'Option',
        options.map((option) => ({
          name: option.flags,
          description: describe({ ...option, required: option.mandatory }),
          // Commander defaults a negated `--no-x` flag to true, which reads backwards in a table
          default: option.flags.includes('--no-') ? undefined : option.default,
        })),
      ),
    )
  }

  return lines
}

export const renderPage = (page: CommandPage, version: string): string =>
  [
    GENERATED_NOTICE,
    '',
    `# ${page.title}`,
    '',
    `${sentence(page.description)} Generated from \`@scalar/cli\` ${version}.`,
    '',
    ...table(
      ['Command', 'Description'],
      page.commands.map((command) => [
        `[${code(command.command)}](#${anchor(commandHeading(command, page))})`,
        escapeCell(phrase(command.description)),
      ]),
    ),
    '',
    ...page.commands.flatMap((command) => [...renderCommand(command, page), '']),
  ].join('\n')

export const renderIndex = (pages: CommandPage[], version: string): string =>
  [
    GENERATED_NOTICE,
    '',
    '# Commands',
    '',
    `Every command in \`@scalar/cli\` ${version}. Run \`scalar <command> --help\` for the same details in your terminal, or \`scalar context\` to get the whole tree as JSON for an AI agent.`,
    '',
    ...pages.flatMap((page) => [
      `## [${page.title}](commands/${page.slug}.md)`,
      '',
      sentence(page.description),
      '',
      ...page.commands.map(
        (command) =>
          `- [${code(command.command)}](commands/${page.slug}.md#${anchor(commandHeading(command, page))}): ${phrase(command.description)}`,
      ),
      '',
    ]),
  ].join('\n')

/**
 * Writes `commands.md` and one page per command group into `commands/`.
 *
 * The `commands/` directory is owned by this script: stale pages for removed groups are deleted.
 */
export const writeCliDocs = async (context: CliContext, outputDirectory: string) => {
  const pages = groupIntoPages(context)
  const pagesDirectory = path.join(outputDirectory, 'commands')

  await fs.rm(pagesDirectory, { recursive: true, force: true })
  await fs.mkdir(pagesDirectory, { recursive: true })

  await Promise.all([
    fs.writeFile(path.join(outputDirectory, 'commands.md'), renderIndex(pages, context.version)),
    ...pages.map((page) =>
      fs.writeFile(path.join(pagesDirectory, `${page.slug}.md`), renderPage(page, context.version)),
    ),
  ])

  return pages
}

export const generateCliDocs = new Command('generate-cli-docs')
  .description('Generate the CLI command reference from `scalar context` output')
  .requiredOption('-c, --context <file>', 'JSON written by `scalar context`')
  .option('-o, --output <directory>', 'Directory for commands.md and commands/', DEFAULT_OUTPUT)
  .action(async ({ context: contextPath, output }: { context: string; output: string }) => {
    const root = getWorkspaceRoot()
    const context = cliContextSchema.parse(
      JSON.parse(await fs.readFile(path.resolve(process.cwd(), contextPath), 'utf-8')),
    )

    const pages = await writeCliDocs(context, path.resolve(root, output))

    console.log(as.green(`Generated ${pages.length} command pages for @scalar/cli ${context.version}`))
  })
