openapi: 3.1.0
info:
  title: Folders
  version: 1.0.0
tags:
  - name: my-tag
    description: 'My tag description'
  - name: my-nested-tag
    description: 'My nested tag description'
  - name: my-second-nested-tag
    description: 'My second nested tag description'
    x-scalar-nested:
      - tagName: my-nested-tag
paths:
  '/foobar':
    get:
      summary: 'GET /foobar'
      tags:
        - tagName: my-nested-tag
    post:
      operationId: the-post
      summary: 'POST /foobar'
      tags:
        - tagName: my-second-nested-tag
    delete:
      operationId: delete-post
      summary: 'POST /foobar'
      tags:
        - tagName: my-tag
