openapi: 3.1.0
info:
  title: Environments
  version: 1.0.0
x-scalar-active-environment: staging
# Secrets will be defined separately from variables
# All environments will inherit the same secrets
# We will provide an interface for fetching secrets from a secret manager (Scalar hosted for now)
x-scalar-secrets:
  apiKey:
    description: 'API key'
    example: '1234567890'
x-scalar-environments:
  production:
    description: 'Production environment'
    color: '#0082D0'
    # Variables are saved directly to the specification
    variables:
      userId:
        description: 'User ID'
        default: '1234567890'
      apiUrl:
        description: 'API URL'
        default: 'https://api.production.example.com'
  staging:
    description: 'Staging environment'
    variables:
      userId: '1234567890'
      apiUrl:
        description: 'API URL'
        default: 'https://api.staging.example.com'
paths:
  '/foobar':
    get:
      summary: 'GET /foobar'
    post:
      operationId: the-post
      summary: 'POST /foobar'
    delete:
      operationId: delete-post
      summary: 'POST /foobar'
