using System.ComponentModel;

namespace Scalar.AspNetCore;

public enum ScalarClients
{
    [Description("libcurl")]
    LIBCURL,
    [Description("clj_http")]
    CLJ_HTTP,
    [Description("httpclient")]
    HTTPCLIENT,
    [Description("restsharp")]
    RESTSHARP,
    [Description("native")]
    NATIVE,
    [Description("http1.1")]
    HTTP1_1,
    [Description("asynchttp")]
    ASYNCHTTP,
    [Description("nethttp")]
    NETHTTP,
    [Description("okhttp")]
    OKHTTP,
    [Description("unirest")]
    UNIREST,
    [Description("xhr")]
    XHR,
    [Description("axios")]
    AXIOS,
    [Description("fetch")]
    FETCH,
    [Description("jquery")]
    JQUERY,
    [Description("undici")]
    UNDICI,
    [Description("request")]
    REQUEST,
    [Description("nsurlsession")]
    NSURLSESSION,
    [Description("cohttp")]
    COHTTP,
    [Description("curl")]
    CURL,
    [Description("guzzle")]
    GUZZLE,
    [Description("http1")]
    HTTP1,
    [Description("http2")]
    HTTP2,
    [Description("webrequest")]
    WEBREQUEST,
    [Description("restmethod")]
    RESTMETHOD,
    [Description("python3")]
    PYTHON3,
    [Description("requests")]
    REQUESTS,
    [Description("httr")]
    HTTR,
    [Description("httpie")]
    HTTPIE,
    [Description("wget")]
    WGET
}