/**
 * This file is autogenerated. Do not edit it.
 *
 * Generated at: 2026-05-20T20:41:54.922Z
 */

/**
 * Whether a parameter example is disabled in the API client (`true` = not sent).
 *
 * @example
 * ```yaml
 * x-disabled: true
 * ```
 */
export type XDisabled = {
  /** When true, the parameter example is not sent with the request */
  'x-disabled'?: boolean
}
