/**
 * Build the source of `esm.js`, the short CDN entry point at the package root, for one package version.
 *
 * `vite.standalone.esm.config.ts` writes the result next to the bundle it points at, so the version
 * baked into the entry point always matches that bundle.
 *
 * jsDelivr serves an unversioned (or semver range) URL such as
 * `https://cdn.jsdelivr.net/npm/@scalar/api-reference/esm.js` from a cache: browsers keep it for a
 * week and the CDN edges for hours after a release. The bundle imports its content-hashed chunks by
 * relative URL, so an entry point cached from an older release requests chunk names that only exist
 * in that release, and jsDelivr resolves those unversioned chunk URLs against the newest release
 * instead. The result is a 404 that breaks every lazily loaded feature (Copy as Markdown, for
 * example) until the caches expire.
 *
 * The generated entry point therefore loads the bundle from a URL pinned to its own version whenever
 * jsDelivr serves it unversioned, which keeps every chunk on that same release. Everywhere else (a
 * pinned CDN URL, or a self-hosted copy) the bundle stays next to the entry point.
 */
export const createEsmEntry = (version: string): string => `/**
 * Short CDN entry point for the ESM standalone build.
 *
 * This thin pointer lives at the package root so the API Reference can be loaded
 * from a friendly URL:
 *
 *   import { createApiReference } from 'https://cdn.jsdelivr.net/npm/@scalar/api-reference/esm.js'
 *
 * The real bundle (and its lazy chunks) stays under \`dist/browser\`. This file is
 * generated by \`vite.standalone.esm.config.ts\`, so the version below is always the
 * version of the bundle that was built next to it.
 *
 * jsDelivr serves an unversioned (or semver range) URL like the one above from a
 * cache: browsers keep it for a week and the CDN edges for hours after a release.
 * The bundle imports its content-hashed chunks by relative URL, so an entry point
 * cached from an older release requests chunk names that only exist in that
 * release, and jsDelivr resolves those unversioned chunk URLs against the newest
 * release instead: a 404 that breaks every lazily loaded feature until the caches
 * expire. So when jsDelivr serves this file unversioned, it loads the bundle from a
 * URL pinned to its own version, which keeps every chunk on that same release.
 * Everywhere else (a pinned CDN URL, or a self-hosted copy) the bundle stays next
 * to this file.
 *
 * Importing the bundle also evaluates it, so its side effects (registering
 * \`window.Scalar\` and reading legacy \`data-*\` attributes) still run.
 */
const version = ${JSON.stringify(version)}
const url = new URL(import.meta.url)
const cdn = /(^|\\.)jsdelivr\\.net$/.test(url.hostname)
  ? /^\\/npm\\/@scalar\\/api-reference(@[^/]*)?\\/esm(\\.min)?\\.js$/.exec(url.pathname)
  : null
const bundle =
  cdn && cdn[1] !== '@' + version
    ? url.origin + '/npm/@scalar/api-reference@' + version + '/dist/browser/standalone.esm.js'
    : new URL('./dist/browser/standalone.esm.js', url).href
const { createApiReference } = await import(bundle)

export { createApiReference }
`
