export { ERRORS, type ErrorResponse, normalizeError } from '@scalar/helpers/errors/normalize-error'

export { type ApiClient, type CreateApiClientParams, type OpenClientPayload, createApiClient } from './create-client'
export { type EnvConfig, type EnvVariables, getEnvColor } from './env-helpers'
export { parseEnvVariables } from './environment-parser'
export { type EventBus, type EventBusListener, createEventBus } from './event-bus'
export { findRequestByPathMethod } from './find-request'
export { type OpenApiDocumentDetails, getOpenApiDocumentDetails } from './getOpenApiDocumentDetails'
export { DEFAULT_HOTKEYS, type HotKeyEvent, getModifiers, handleHotKeyDown, isInput } from './hot-keys'
export { isUrl } from './isUrl'
export { loadAllResources } from './local-storage'
export { formatHeaderKey, normalizeHeaders } from './normalize-headers'
export { parseCurlCommand } from './parse-curl'
export { convertPostmanToOpenApi, getPostmanDocumentDetails, isPostmanCollection } from './postman'
export { type RequestStatus, buildRequestSecurity, createRequestOperation, decodeBuffer } from './send-request'
