import type { OAuthFlowsObject } from './oauth-flows'

type Description = {
  /** A short description for security scheme. CommonMark syntax MAY be used for rich text representation. */
  description?: string
}

// Simple security schemes with no additional required fields

export type UserPasswordObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'userPassword'
}

export type X509Object = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'X509'
}

export type SymmetricEncryptionObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'symmetricEncryption'
}

export type AsymmetricEncryptionObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'asymmetricEncryption'
}

export type PlainObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'plain'
}

export type ScramSha256Object = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'scramSha256'
}

export type ScramSha512Object = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'scramSha512'
}

export type GssapiObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'gssapi'
}

// Security schemes with additional required fields

export type ApiKeyObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'apiKey'
  /** REQUIRED. The location of the API key. Valid values are "user" and "password". */
  in: 'user' | 'password'
}

export type HttpApiKeyObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'httpApiKey'
  /** REQUIRED. The name of the header, query or cookie parameter to be used. */
  name: string
  /** REQUIRED. The location of the API key. Valid values are "query", "header", or "cookie". */
  in: 'query' | 'header' | 'cookie'
}

export type HttpObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'http'
  /** REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in RFC7235. */
  scheme: string
  /** A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes. */
  bearerFormat?: string
}

export type OAuth2Object = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'oauth2'
  /** REQUIRED. An object containing configuration information for the flow types supported. */
  flows: OAuthFlowsObject
  /** List of the needed scope names. An empty array means no scopes are needed. */
  scopes?: string[]
}

export type OpenIdConnectObject = Description & {
  /** REQUIRED. The type of the security scheme. */
  type: 'openIdConnect'
  /** REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of an absolute URL. */
  openIdConnectUrl: string
  /** List of the needed scope names. An empty array means no scopes are needed. */
  scopes?: string[]
}

/**
 * Defines a security scheme that can be used by the operations.
 *
 * Supported schemes are:
 * - User/Password
 * - API key (either as user or as password)
 * - X.509 certificate
 * - End-to-end encryption (either symmetric or asymmetric)
 * - HTTP authentication
 * - HTTP API key
 * - OAuth2's common flows (Implicit, Resource Owner Protected Credentials, Client Credentials and Authorization Code) as defined in RFC6749
 * - OpenID Connect Discovery
 * - SASL (Simple Authentication and Security Layer) as defined in RFC4422
 */
export type SecuritySchemeObject =
  | UserPasswordObject
  | ApiKeyObject
  | X509Object
  | SymmetricEncryptionObject
  | AsymmetricEncryptionObject
  | HttpApiKeyObject
  | HttpObject
  | OAuth2Object
  | OpenIdConnectObject
  | PlainObject
  | ScramSha256Object
  | ScramSha512Object
  | GssapiObject
