import type { EnumDef, FieldDef, ModelDef } from './types'

const HEADER = `# This file is auto-generated by the Scalar Python config generator.
# Command: pnpm script generate-python-config
#
# Do not edit this file manually. Changes will be lost when the file is regenerated.
# Source of truth: packages/types/src/api-reference/`

// ---------------------------------------------------------------------------
// enums.py
// ---------------------------------------------------------------------------

export function emitEnums(enums: EnumDef[]): string {
  const lines: string[] = [HEADER, '', 'from enum import Enum', '']

  for (const [i, enumDef] of enums.entries()) {
    if (i > 0) {
      lines.push('')
    }
    lines.push('')
    lines.push(`class ${enumDef.className}(Enum):`)
    for (const member of enumDef.members) {
      lines.push(`    ${member.memberName} = "${member.value}"`)
    }
  }

  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// models.py
// ---------------------------------------------------------------------------

export function emitModels(models: ModelDef[]): string {
  const lines: string[] = [HEADER, '']

  // Collect all needed typing imports
  const typingImports = collectTypingImports(models.flatMap((m) => m.fields))
  lines.push(`from typing import ${typingImports.join(', ')}`)
  lines.push('')
  lines.push('from pydantic import BaseModel, ConfigDict, Field')
  lines.push('')
  lines.push('from .enums import Layout, SearchHotKey, Theme')

  for (const model of models) {
    lines.push('')
    lines.push('')
    lines.push(`class ${model.className}(BaseModel):`)
    lines.push(`    """`)
    for (const docLine of model.docstring.split('\n')) {
      lines.push(`    ${docLine}`)
    }
    lines.push(`    """`)
    lines.push('')

    if (model.forbidExtra) {
      lines.push(`    model_config = ConfigDict(extra="forbid")`)
      lines.push('')
    }

    for (const [i, field] of model.fields.entries()) {
      lines.push(emitField(field))
      if (i < model.fields.length - 1) {
        lines.push('')
      }
    }
  }

  lines.push('')
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// config.py
// ---------------------------------------------------------------------------

export function emitConfig(config: ModelDef): string {
  const lines: string[] = [HEADER, '']

  // Collect typing imports
  const typingImports = collectTypingImports(config.fields)
  lines.push(`from typing import ${typingImports.join(', ')}`)
  lines.push('')
  lines.push('from pydantic import BaseModel, ConfigDict, Field')
  lines.push('')

  for (const imp of config.imports) {
    lines.push(`from ${imp.from} import ${imp.names.join(', ')}`)
  }

  lines.push('')
  lines.push('')
  lines.push(`class ${config.className}(BaseModel):`)
  lines.push(`    """${config.docstring}"""`)
  lines.push('')

  if (config.forbidExtra) {
    lines.push('    model_config = ConfigDict(')
    lines.push('        extra="forbid",')
    lines.push('        use_enum_values=False,')
    lines.push('    )')
    lines.push('')
  }

  for (const [i, field] of config.fields.entries()) {
    lines.push(emitField(field))
    if (i < config.fields.length - 1) {
      lines.push('')
    }
  }

  lines.push('')

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function emitField(field: FieldDef): string {
  const parts: string[] = []

  if (field.useFactory) {
    parts.push(`default_factory=${field.defaultValue}`)
  } else {
    parts.push(`default=${field.defaultValue}`)
  }

  if (field.description) {
    // Escape quotes in description
    const desc = field.description.replace(/"/g, '\\"')
    parts.push(`description="${desc}"`)
  }

  return `    ${field.name}: ${field.pythonType} = Field(\n        ${parts.join(',\n        ')},\n    )`
}

function collectTypingImports(fields: FieldDef[]): string[] {
  const needed = new Set<string>()

  for (const field of fields) {
    const type = field.pythonType
    if (type.includes('Any')) needed.add('Any')
    if (type.includes('Dict[')) needed.add('Dict')
    if (type.includes('List[')) needed.add('List')
    if (type.includes('Literal[')) needed.add('Literal')
    if (type.includes('Optional[')) needed.add('Optional')
    if (type.includes('Union[')) needed.add('Union')
  }

  // Sort for consistent output
  return [...needed].sort()
}
