name: Deploy Scalar examples

on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Deploy Scalar examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install netlify
        run: pnpm install -g netlify
      - name: Generate Run UUID
        run: echo "DEPLOY_ID=$(uuidgen)" >> "$GITHUB_ENV" && echo $DEPLOY_ID
      - name: Install dependencies
        run: pnpm --filter web install
      - name: Restore Turborepo cache
        uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-node-${{ matrix.node-version }}
      - name: Build
        run: cd examples/web && pnpm turbo run build
        env:
          DEPLOY_ID: ${{ env.DEPLOY_ID }}
      - name: Deploy to netlify
        run: |
          netlify deploy --dir "./examples/web/dist" \
            --message "Deployed from GitHub (${{ env.DEPLOY_ID }})" \
            --site ${{ vars.NETLIFY_SITE_ID_PREVIEW }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --filter @scalar-examples/web --prod
