name: Deploy Storybook

on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Deploy Scalar Components Storybook
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install netlify
        run: pnpm install -g netlify
      - name: Generate Run UUID
        run: echo "DEPLOY_ID=$(uuidgen)" >> "$GITHUB_ENV" && echo $DEPLOY_ID
      - name: Install dependencies
        run: pnpm --filter components... install
      - name: Build components and dependencies
        run: pnpm --filter components... build
      - name: Build storybook
        run: pnpm --filter components build:storybook
        env:
          DEPLOY_ID: ${{ env.DEPLOY_ID }}
      - name: Deploy Storybook to Netlify (Production)
        run: |
          netlify deploy --dir "./packages/components/storybook-static" \
            --message "Deployed from GitHub (${{ env.DEPLOY_ID }})" \
            --site ${{ vars.NETLIFY_SITE_ID_COMPONENTS }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            --filter @scalar/components --prod
