name: Build Electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Turborepo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-node-20
      - name: Build packages
        run: pnpm build:packages
      - name: Build Electron for ${{ matrix.os }}
        run: pnpm --filter scalar-api-client build:mac
        env:
          # The base64-encoded data of the certificate (*.p12 or *.pfx file).
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          # The password to decrypt the certificate given in CSC_LINK.
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          # The username of your Apple Developer account
          APPLE_ID: ${{ secrets.APPLE_ID }}
          # https://support.apple.com/en-us/102654
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          # https://developer.apple.com/help/account/manage-your-team/locate-your-team-id/
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
