name: Lint the PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 15
    steps:
      # https://github.com/marketplace/actions/semantic-pull-request
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
