name: Lint the PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/semantic-pull-request
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
