name: Publish on Stackblitz

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    if: github.head_ref == 'changeset-release/main'

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Turborepo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-node-20
          restore-keys: |
            ${{ runner.os }}-turbo-node-
      - name: Build packages
        run: pnpm build:packages
      - name: Publish on Stackblitz
        # TODO: Fails on non-npm packages (see: https://github.com/stackblitz-labs/pkg.pr.new/issues/116)
        # run: npx pkg-pr-new publish ./packages/*
        # TODO: We can’t pass multiple lines (see: https://github.com/stackblitz-labs/pkg.pr.new/issues/117)
        run: npx pkg-pr-new publish ./packages/api-client ./packages/api-reference ./packages/api-reference-editor ./packages/api-reference-react ./packages/build-tooling ./packages/cli ./packages/code-highlight ./packages/components ./packages/docusaurus ./packages/draggable ./packages/express-api-reference ./packages/fastify-api-reference ./packages/galaxy ./packages/hono-api-reference ./packages/mock-server ./packages/nestjs-api-reference ./packages/nextjs-api-reference ./packages/nuxt ./packages/oas-utils ./packages/object-utils ./packages/play-button ./packages/themes ./packages/use-codemirror ./packages/use-toasts ./packages/use-tooltip ./packages/void-server
