name: Update Scalar CLI Documentation

on:
  # Run every hour
  schedule:
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-cli-docs:
    name: Update CLI Documentation
    if: ${{ github.repository_owner == 'scalar' }}
    runs-on: blacksmith-2vcpu-ubuntu-2204
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Generate CLI documentation
        run: npx @scalar/cli@latest readme generate --output README.md
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet README.md; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request
        if: steps.check-changes.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          commit-message: 'docs(cli): update commands'
          title: 'docs(cli): update commands'
          body: |
            This PR updates the CLI commands documentation by running the latest version of @scalar/cli.

            Changes were automatically generated by the CLI's `readme generate` command.

            **This PR was automatically created by a scheduled workflow.**
          branch: docs/update-cli-documentation
          delete-branch: true
